// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cache.proto

#ifndef PROTOBUF_INCLUDED_cache_2eproto
#define PROTOBUF_INCLUDED_cache_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_cache_2eproto 

namespace protobuf_cache_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
}  // namespace protobuf_cache_2eproto
namespace wbapi {
class UidsOfFamilyStore;
class UidsOfFamilyStoreDefaultTypeInternal;
extern UidsOfFamilyStoreDefaultTypeInternal _UidsOfFamilyStore_default_instance_;
}  // namespace wbapi
namespace google {
namespace protobuf {
template<> ::wbapi::UidsOfFamilyStore* Arena::CreateMaybeMessage<::wbapi::UidsOfFamilyStore>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace wbapi {

// ===================================================================

class UidsOfFamilyStore : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.UidsOfFamilyStore) */ {
 public:
  UidsOfFamilyStore();
  virtual ~UidsOfFamilyStore();

  UidsOfFamilyStore(const UidsOfFamilyStore& from);

  inline UidsOfFamilyStore& operator=(const UidsOfFamilyStore& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UidsOfFamilyStore(UidsOfFamilyStore&& from) noexcept
    : UidsOfFamilyStore() {
    *this = ::std::move(from);
  }

  inline UidsOfFamilyStore& operator=(UidsOfFamilyStore&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const UidsOfFamilyStore& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UidsOfFamilyStore* internal_default_instance() {
    return reinterpret_cast<const UidsOfFamilyStore*>(
               &_UidsOfFamilyStore_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(UidsOfFamilyStore* other);
  friend void swap(UidsOfFamilyStore& a, UidsOfFamilyStore& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UidsOfFamilyStore* New() const final {
    return CreateMaybeMessage<UidsOfFamilyStore>(NULL);
  }

  UidsOfFamilyStore* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UidsOfFamilyStore>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const UidsOfFamilyStore& from);
  void MergeFrom(const UidsOfFamilyStore& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UidsOfFamilyStore* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 user_ids = 1;
  int user_ids_size() const;
  void clear_user_ids();
  static const int kUserIdsFieldNumber = 1;
  ::google::protobuf::int64 user_ids(int index) const;
  void set_user_ids(int index, ::google::protobuf::int64 value);
  void add_user_ids(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      user_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_user_ids();

  // repeated int64 gw_ids = 2;
  int gw_ids_size() const;
  void clear_gw_ids();
  static const int kGwIdsFieldNumber = 2;
  ::google::protobuf::int64 gw_ids(int index) const;
  void set_gw_ids(int index, ::google::protobuf::int64 value);
  void add_gw_ids(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      gw_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_gw_ids();

  // @@protoc_insertion_point(class_scope:wbapi.UidsOfFamilyStore)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > user_ids_;
  mutable int _user_ids_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > gw_ids_;
  mutable int _gw_ids_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cache_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UidsOfFamilyStore

// repeated int64 user_ids = 1;
inline int UidsOfFamilyStore::user_ids_size() const {
  return user_ids_.size();
}
inline void UidsOfFamilyStore::clear_user_ids() {
  user_ids_.Clear();
}
inline ::google::protobuf::int64 UidsOfFamilyStore::user_ids(int index) const {
  // @@protoc_insertion_point(field_get:wbapi.UidsOfFamilyStore.user_ids)
  return user_ids_.Get(index);
}
inline void UidsOfFamilyStore::set_user_ids(int index, ::google::protobuf::int64 value) {
  user_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:wbapi.UidsOfFamilyStore.user_ids)
}
inline void UidsOfFamilyStore::add_user_ids(::google::protobuf::int64 value) {
  user_ids_.Add(value);
  // @@protoc_insertion_point(field_add:wbapi.UidsOfFamilyStore.user_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
UidsOfFamilyStore::user_ids() const {
  // @@protoc_insertion_point(field_list:wbapi.UidsOfFamilyStore.user_ids)
  return user_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
UidsOfFamilyStore::mutable_user_ids() {
  // @@protoc_insertion_point(field_mutable_list:wbapi.UidsOfFamilyStore.user_ids)
  return &user_ids_;
}

// repeated int64 gw_ids = 2;
inline int UidsOfFamilyStore::gw_ids_size() const {
  return gw_ids_.size();
}
inline void UidsOfFamilyStore::clear_gw_ids() {
  gw_ids_.Clear();
}
inline ::google::protobuf::int64 UidsOfFamilyStore::gw_ids(int index) const {
  // @@protoc_insertion_point(field_get:wbapi.UidsOfFamilyStore.gw_ids)
  return gw_ids_.Get(index);
}
inline void UidsOfFamilyStore::set_gw_ids(int index, ::google::protobuf::int64 value) {
  gw_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:wbapi.UidsOfFamilyStore.gw_ids)
}
inline void UidsOfFamilyStore::add_gw_ids(::google::protobuf::int64 value) {
  gw_ids_.Add(value);
  // @@protoc_insertion_point(field_add:wbapi.UidsOfFamilyStore.gw_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
UidsOfFamilyStore::gw_ids() const {
  // @@protoc_insertion_point(field_list:wbapi.UidsOfFamilyStore.gw_ids)
  return gw_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
UidsOfFamilyStore::mutable_gw_ids() {
  // @@protoc_insertion_point(field_mutable_list:wbapi.UidsOfFamilyStore.gw_ids)
  return &gw_ids_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace wbapi

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_cache_2eproto
