// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error_code.proto

#ifndef PROTOBUF_INCLUDED_error_5fcode_2eproto
#define PROTOBUF_INCLUDED_error_5fcode_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_error_5fcode_2eproto 

namespace protobuf_error_5fcode_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
}  // namespace protobuf_error_5fcode_2eproto
namespace wbapi {
}  // namespace wbapi
namespace wbapi {

enum ErrorCode {
  ERR_SUCCEED = 0,
  ERR_FAILED = 10000,
  ERR_SYSTEM_ERROR = 10001,
  ERR_SYSTEM_UNAVALIABLE = 10002,
  ERR_REMOTE_SERVICE_ERROR = 10003,
  ERR_PERMISSION_DENIED = 10004,
  ERR_PARAMETER_ERROR = 10005,
  ERR_TOO_MANY_TASKS = 10006,
  ERR_TASK_EXPIRED = 10007,
  ERR_RPC_ERROR = 10008,
  ERR_INVALID_REQUEST = 10009,
  ERR_INVALID_APP_KEY = 10010,
  ERR_REQUEST_BODY_TOO_LARGE = 10011,
  ERR_METHOD_NOT_SUPPORT = 10012,
  ERR_OUT_OF_RATE_LIMIT = 10013,
  ERR_INVALID_MOBILE = 10014,
  ERR_PASSWD_LENGTH_ERROR = 10015,
  ERR_VERIFY_CODE_SEND_FAILED = 10016,
  ERR_INVALID_VERIFY_CODE = 10017,
  ERR_USER_ALREADY_EXISTS = 10018,
  ERR_PASSWD_ERROR = 10019,
  ERR_APP_NOT_EXISTS = 10020,
  ERR_USER_NOT_EXISTS = 10021,
  ERR_REGISTER_FAILED = 10022,
  ERR_INVALID_TOKEN = 10023,
  ERR_INVALID_AVATAR_TYPE = 10024,
  ERR_INVALID_CLIENT_TYPE = 10025,
  ERR_DB_ERROR = 10026,
  ERR_VERIFY_CODE_TMPL_NOT_EXISTS = 10027,
  ERR_MSG_ERROR = 10028,
  ERR_SERIAL_NUMBER_ERROR = 20001,
  ERR_INVALID_IEEE = 20002,
  ERR_MODEL_ERROR = 20003,
  ERR_GATEWAY_ALREADY_EXISTS = 20004,
  ERR_GATEWAY_NOT_EXISTS = 20005,
  ERR_OFFLINE = 20006,
  ERR_FAMILY_NOT_EXISTS = 20007,
  ERR_ROOM_NOT_EXISTS = 20008,
  ERR_DEVICE_NOT_EXISTS = 20009,
  ERR_INVALID_DEVICE_TYPE = 20010,
  ERR_GATEWAY_IN_OTHER_FAMILY = 20011,
  ERR_DEVICE_IN_OTHER_FAMILY = 20012,
  ERR_DEVICE_IN_OTHER_GATEWAY = 20013,
  ERR_NOT_FAMILY_MASTER = 20014,
  ERR_DELETE_CURRENT_FAMILY = 20015,
  ErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ErrorCode_IsValid(int value);
const ErrorCode ErrorCode_MIN = ERR_SUCCEED;
const ErrorCode ErrorCode_MAX = ERR_DELETE_CURRENT_FAMILY;
const int ErrorCode_ARRAYSIZE = ErrorCode_MAX + 1;

// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace wbapi

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::wbapi::ErrorCode> : ::std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_error_5fcode_2eproto
