// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hfonts.proto

#ifndef PROTOBUF_INCLUDED_hfonts_2eproto
#define PROTOBUF_INCLUDED_hfonts_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_hfonts_2eproto 

namespace protobuf_hfonts_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
}  // namespace protobuf_hfonts_2eproto
namespace wbapi {
class IconFontBitmapGetRequest;
class IconFontBitmapGetRequestDefaultTypeInternal;
extern IconFontBitmapGetRequestDefaultTypeInternal _IconFontBitmapGetRequest_default_instance_;
class IconFontBitmapGetResponse;
class IconFontBitmapGetResponseDefaultTypeInternal;
extern IconFontBitmapGetResponseDefaultTypeInternal _IconFontBitmapGetResponse_default_instance_;
}  // namespace wbapi
namespace google {
namespace protobuf {
template<> ::wbapi::IconFontBitmapGetRequest* Arena::CreateMaybeMessage<::wbapi::IconFontBitmapGetRequest>(Arena*);
template<> ::wbapi::IconFontBitmapGetResponse* Arena::CreateMaybeMessage<::wbapi::IconFontBitmapGetResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace wbapi {

enum IconFontBitmapType {
  ICON_FONT_BITMAP_TYPE_ICON = 0,
  ICON_FONT_BITMAP_TYPE_FONT = 1,
  IconFontBitmapType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  IconFontBitmapType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool IconFontBitmapType_IsValid(int value);
const IconFontBitmapType IconFontBitmapType_MIN = ICON_FONT_BITMAP_TYPE_ICON;
const IconFontBitmapType IconFontBitmapType_MAX = ICON_FONT_BITMAP_TYPE_FONT;
const int IconFontBitmapType_ARRAYSIZE = IconFontBitmapType_MAX + 1;

// ===================================================================

class IconFontBitmapGetRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.IconFontBitmapGetRequest) */ {
 public:
  IconFontBitmapGetRequest();
  virtual ~IconFontBitmapGetRequest();

  IconFontBitmapGetRequest(const IconFontBitmapGetRequest& from);

  inline IconFontBitmapGetRequest& operator=(const IconFontBitmapGetRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  IconFontBitmapGetRequest(IconFontBitmapGetRequest&& from) noexcept
    : IconFontBitmapGetRequest() {
    *this = ::std::move(from);
  }

  inline IconFontBitmapGetRequest& operator=(IconFontBitmapGetRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const IconFontBitmapGetRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IconFontBitmapGetRequest* internal_default_instance() {
    return reinterpret_cast<const IconFontBitmapGetRequest*>(
               &_IconFontBitmapGetRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(IconFontBitmapGetRequest* other);
  friend void swap(IconFontBitmapGetRequest& a, IconFontBitmapGetRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline IconFontBitmapGetRequest* New() const final {
    return CreateMaybeMessage<IconFontBitmapGetRequest>(NULL);
  }

  IconFontBitmapGetRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<IconFontBitmapGetRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const IconFontBitmapGetRequest& from);
  void MergeFrom(const IconFontBitmapGetRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IconFontBitmapGetRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .wbapi.IconFontBitmapType type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::wbapi::IconFontBitmapType type() const;
  void set_type(::wbapi::IconFontBitmapType value);

  // uint32 code = 2;
  void clear_code();
  static const int kCodeFieldNumber = 2;
  ::google::protobuf::uint32 code() const;
  void set_code(::google::protobuf::uint32 value);

  // int32 device_id = 3;
  void clear_device_id();
  static const int kDeviceIdFieldNumber = 3;
  ::google::protobuf::int32 device_id() const;
  void set_device_id(::google::protobuf::int32 value);

  // int32 sub_id = 4;
  void clear_sub_id();
  static const int kSubIdFieldNumber = 4;
  ::google::protobuf::int32 sub_id() const;
  void set_sub_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wbapi.IconFontBitmapGetRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  int type_;
  ::google::protobuf::uint32 code_;
  ::google::protobuf::int32 device_id_;
  ::google::protobuf::int32 sub_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_hfonts_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class IconFontBitmapGetResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.IconFontBitmapGetResponse) */ {
 public:
  IconFontBitmapGetResponse();
  virtual ~IconFontBitmapGetResponse();

  IconFontBitmapGetResponse(const IconFontBitmapGetResponse& from);

  inline IconFontBitmapGetResponse& operator=(const IconFontBitmapGetResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  IconFontBitmapGetResponse(IconFontBitmapGetResponse&& from) noexcept
    : IconFontBitmapGetResponse() {
    *this = ::std::move(from);
  }

  inline IconFontBitmapGetResponse& operator=(IconFontBitmapGetResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const IconFontBitmapGetResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IconFontBitmapGetResponse* internal_default_instance() {
    return reinterpret_cast<const IconFontBitmapGetResponse*>(
               &_IconFontBitmapGetResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(IconFontBitmapGetResponse* other);
  friend void swap(IconFontBitmapGetResponse& a, IconFontBitmapGetResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline IconFontBitmapGetResponse* New() const final {
    return CreateMaybeMessage<IconFontBitmapGetResponse>(NULL);
  }

  IconFontBitmapGetResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<IconFontBitmapGetResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const IconFontBitmapGetResponse& from);
  void MergeFrom(const IconFontBitmapGetResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IconFontBitmapGetResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes bitmap = 6;
  void clear_bitmap();
  static const int kBitmapFieldNumber = 6;
  const ::std::string& bitmap() const;
  void set_bitmap(const ::std::string& value);
  #if LANG_CXX11
  void set_bitmap(::std::string&& value);
  #endif
  void set_bitmap(const char* value);
  void set_bitmap(const void* value, size_t size);
  ::std::string* mutable_bitmap();
  ::std::string* release_bitmap();
  void set_allocated_bitmap(::std::string* bitmap);

  // int32 error_code = 1;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 error_code() const;
  void set_error_code(::google::protobuf::int32 value);

  // .wbapi.IconFontBitmapType type = 2;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::wbapi::IconFontBitmapType type() const;
  void set_type(::wbapi::IconFontBitmapType value);

  // uint32 code = 3;
  void clear_code();
  static const int kCodeFieldNumber = 3;
  ::google::protobuf::uint32 code() const;
  void set_code(::google::protobuf::uint32 value);

  // uint32 section = 4;
  void clear_section();
  static const int kSectionFieldNumber = 4;
  ::google::protobuf::uint32 section() const;
  void set_section(::google::protobuf::uint32 value);

  // uint32 index = 5;
  void clear_index();
  static const int kIndexFieldNumber = 5;
  ::google::protobuf::uint32 index() const;
  void set_index(::google::protobuf::uint32 value);

  // int32 device_id = 7;
  void clear_device_id();
  static const int kDeviceIdFieldNumber = 7;
  ::google::protobuf::int32 device_id() const;
  void set_device_id(::google::protobuf::int32 value);

  // int32 sub_id = 8;
  void clear_sub_id();
  static const int kSubIdFieldNumber = 8;
  ::google::protobuf::int32 sub_id() const;
  void set_sub_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wbapi.IconFontBitmapGetResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr bitmap_;
  ::google::protobuf::int32 error_code_;
  int type_;
  ::google::protobuf::uint32 code_;
  ::google::protobuf::uint32 section_;
  ::google::protobuf::uint32 index_;
  ::google::protobuf::int32 device_id_;
  ::google::protobuf::int32 sub_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_hfonts_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IconFontBitmapGetRequest

// .wbapi.IconFontBitmapType type = 1;
inline void IconFontBitmapGetRequest::clear_type() {
  type_ = 0;
}
inline ::wbapi::IconFontBitmapType IconFontBitmapGetRequest::type() const {
  // @@protoc_insertion_point(field_get:wbapi.IconFontBitmapGetRequest.type)
  return static_cast< ::wbapi::IconFontBitmapType >(type_);
}
inline void IconFontBitmapGetRequest::set_type(::wbapi::IconFontBitmapType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:wbapi.IconFontBitmapGetRequest.type)
}

// uint32 code = 2;
inline void IconFontBitmapGetRequest::clear_code() {
  code_ = 0u;
}
inline ::google::protobuf::uint32 IconFontBitmapGetRequest::code() const {
  // @@protoc_insertion_point(field_get:wbapi.IconFontBitmapGetRequest.code)
  return code_;
}
inline void IconFontBitmapGetRequest::set_code(::google::protobuf::uint32 value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:wbapi.IconFontBitmapGetRequest.code)
}

// int32 device_id = 3;
inline void IconFontBitmapGetRequest::clear_device_id() {
  device_id_ = 0;
}
inline ::google::protobuf::int32 IconFontBitmapGetRequest::device_id() const {
  // @@protoc_insertion_point(field_get:wbapi.IconFontBitmapGetRequest.device_id)
  return device_id_;
}
inline void IconFontBitmapGetRequest::set_device_id(::google::protobuf::int32 value) {
  
  device_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.IconFontBitmapGetRequest.device_id)
}

// int32 sub_id = 4;
inline void IconFontBitmapGetRequest::clear_sub_id() {
  sub_id_ = 0;
}
inline ::google::protobuf::int32 IconFontBitmapGetRequest::sub_id() const {
  // @@protoc_insertion_point(field_get:wbapi.IconFontBitmapGetRequest.sub_id)
  return sub_id_;
}
inline void IconFontBitmapGetRequest::set_sub_id(::google::protobuf::int32 value) {
  
  sub_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.IconFontBitmapGetRequest.sub_id)
}

// -------------------------------------------------------------------

// IconFontBitmapGetResponse

// int32 error_code = 1;
inline void IconFontBitmapGetResponse::clear_error_code() {
  error_code_ = 0;
}
inline ::google::protobuf::int32 IconFontBitmapGetResponse::error_code() const {
  // @@protoc_insertion_point(field_get:wbapi.IconFontBitmapGetResponse.error_code)
  return error_code_;
}
inline void IconFontBitmapGetResponse::set_error_code(::google::protobuf::int32 value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:wbapi.IconFontBitmapGetResponse.error_code)
}

// .wbapi.IconFontBitmapType type = 2;
inline void IconFontBitmapGetResponse::clear_type() {
  type_ = 0;
}
inline ::wbapi::IconFontBitmapType IconFontBitmapGetResponse::type() const {
  // @@protoc_insertion_point(field_get:wbapi.IconFontBitmapGetResponse.type)
  return static_cast< ::wbapi::IconFontBitmapType >(type_);
}
inline void IconFontBitmapGetResponse::set_type(::wbapi::IconFontBitmapType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:wbapi.IconFontBitmapGetResponse.type)
}

// uint32 code = 3;
inline void IconFontBitmapGetResponse::clear_code() {
  code_ = 0u;
}
inline ::google::protobuf::uint32 IconFontBitmapGetResponse::code() const {
  // @@protoc_insertion_point(field_get:wbapi.IconFontBitmapGetResponse.code)
  return code_;
}
inline void IconFontBitmapGetResponse::set_code(::google::protobuf::uint32 value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:wbapi.IconFontBitmapGetResponse.code)
}

// uint32 section = 4;
inline void IconFontBitmapGetResponse::clear_section() {
  section_ = 0u;
}
inline ::google::protobuf::uint32 IconFontBitmapGetResponse::section() const {
  // @@protoc_insertion_point(field_get:wbapi.IconFontBitmapGetResponse.section)
  return section_;
}
inline void IconFontBitmapGetResponse::set_section(::google::protobuf::uint32 value) {
  
  section_ = value;
  // @@protoc_insertion_point(field_set:wbapi.IconFontBitmapGetResponse.section)
}

// uint32 index = 5;
inline void IconFontBitmapGetResponse::clear_index() {
  index_ = 0u;
}
inline ::google::protobuf::uint32 IconFontBitmapGetResponse::index() const {
  // @@protoc_insertion_point(field_get:wbapi.IconFontBitmapGetResponse.index)
  return index_;
}
inline void IconFontBitmapGetResponse::set_index(::google::protobuf::uint32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:wbapi.IconFontBitmapGetResponse.index)
}

// bytes bitmap = 6;
inline void IconFontBitmapGetResponse::clear_bitmap() {
  bitmap_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& IconFontBitmapGetResponse::bitmap() const {
  // @@protoc_insertion_point(field_get:wbapi.IconFontBitmapGetResponse.bitmap)
  return bitmap_.GetNoArena();
}
inline void IconFontBitmapGetResponse::set_bitmap(const ::std::string& value) {
  
  bitmap_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:wbapi.IconFontBitmapGetResponse.bitmap)
}
#if LANG_CXX11
inline void IconFontBitmapGetResponse::set_bitmap(::std::string&& value) {
  
  bitmap_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:wbapi.IconFontBitmapGetResponse.bitmap)
}
#endif
inline void IconFontBitmapGetResponse::set_bitmap(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  bitmap_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:wbapi.IconFontBitmapGetResponse.bitmap)
}
inline void IconFontBitmapGetResponse::set_bitmap(const void* value, size_t size) {
  
  bitmap_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:wbapi.IconFontBitmapGetResponse.bitmap)
}
inline ::std::string* IconFontBitmapGetResponse::mutable_bitmap() {
  
  // @@protoc_insertion_point(field_mutable:wbapi.IconFontBitmapGetResponse.bitmap)
  return bitmap_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* IconFontBitmapGetResponse::release_bitmap() {
  // @@protoc_insertion_point(field_release:wbapi.IconFontBitmapGetResponse.bitmap)
  
  return bitmap_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void IconFontBitmapGetResponse::set_allocated_bitmap(::std::string* bitmap) {
  if (bitmap != NULL) {
    
  } else {
    
  }
  bitmap_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bitmap);
  // @@protoc_insertion_point(field_set_allocated:wbapi.IconFontBitmapGetResponse.bitmap)
}

// int32 device_id = 7;
inline void IconFontBitmapGetResponse::clear_device_id() {
  device_id_ = 0;
}
inline ::google::protobuf::int32 IconFontBitmapGetResponse::device_id() const {
  // @@protoc_insertion_point(field_get:wbapi.IconFontBitmapGetResponse.device_id)
  return device_id_;
}
inline void IconFontBitmapGetResponse::set_device_id(::google::protobuf::int32 value) {
  
  device_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.IconFontBitmapGetResponse.device_id)
}

// int32 sub_id = 8;
inline void IconFontBitmapGetResponse::clear_sub_id() {
  sub_id_ = 0;
}
inline ::google::protobuf::int32 IconFontBitmapGetResponse::sub_id() const {
  // @@protoc_insertion_point(field_get:wbapi.IconFontBitmapGetResponse.sub_id)
  return sub_id_;
}
inline void IconFontBitmapGetResponse::set_sub_id(::google::protobuf::int32 value) {
  
  sub_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.IconFontBitmapGetResponse.sub_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace wbapi

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::wbapi::IconFontBitmapType> : ::std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_hfonts_2eproto
