// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hfonts.proto

#include "hfonts.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace wbapi {
class IconFontBitmapGetRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<IconFontBitmapGetRequest>
      _instance;
} _IconFontBitmapGetRequest_default_instance_;
class IconFontBitmapGetResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<IconFontBitmapGetResponse>
      _instance;
} _IconFontBitmapGetResponse_default_instance_;
}  // namespace wbapi
namespace protobuf_hfonts_2eproto {
static void InitDefaultsIconFontBitmapGetRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_IconFontBitmapGetRequest_default_instance_;
    new (ptr) ::wbapi::IconFontBitmapGetRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::IconFontBitmapGetRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_IconFontBitmapGetRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsIconFontBitmapGetRequest}, {}};

static void InitDefaultsIconFontBitmapGetResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_IconFontBitmapGetResponse_default_instance_;
    new (ptr) ::wbapi::IconFontBitmapGetResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::IconFontBitmapGetResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_IconFontBitmapGetResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsIconFontBitmapGetResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_IconFontBitmapGetRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_IconFontBitmapGetResponse.base);
}

}  // namespace protobuf_hfonts_2eproto
namespace wbapi {
bool IconFontBitmapType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void IconFontBitmapGetRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int IconFontBitmapGetRequest::kTypeFieldNumber;
const int IconFontBitmapGetRequest::kCodeFieldNumber;
const int IconFontBitmapGetRequest::kDeviceIdFieldNumber;
const int IconFontBitmapGetRequest::kSubIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

IconFontBitmapGetRequest::IconFontBitmapGetRequest()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_hfonts_2eproto::scc_info_IconFontBitmapGetRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.IconFontBitmapGetRequest)
}
IconFontBitmapGetRequest::IconFontBitmapGetRequest(const IconFontBitmapGetRequest& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&type_, &from.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&sub_id_) -
    reinterpret_cast<char*>(&type_)) + sizeof(sub_id_));
  // @@protoc_insertion_point(copy_constructor:wbapi.IconFontBitmapGetRequest)
}

void IconFontBitmapGetRequest::SharedCtor() {
  ::memset(&type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sub_id_) -
      reinterpret_cast<char*>(&type_)) + sizeof(sub_id_));
}

IconFontBitmapGetRequest::~IconFontBitmapGetRequest() {
  // @@protoc_insertion_point(destructor:wbapi.IconFontBitmapGetRequest)
  SharedDtor();
}

void IconFontBitmapGetRequest::SharedDtor() {
}

void IconFontBitmapGetRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const IconFontBitmapGetRequest& IconFontBitmapGetRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_hfonts_2eproto::scc_info_IconFontBitmapGetRequest.base);
  return *internal_default_instance();
}


void IconFontBitmapGetRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.IconFontBitmapGetRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sub_id_) -
      reinterpret_cast<char*>(&type_)) + sizeof(sub_id_));
  _internal_metadata_.Clear();
}

bool IconFontBitmapGetRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.IconFontBitmapGetRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .wbapi.IconFontBitmapType type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::wbapi::IconFontBitmapType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 code = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 device_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &device_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 sub_id = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sub_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.IconFontBitmapGetRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.IconFontBitmapGetRequest)
  return false;
#undef DO_
}

void IconFontBitmapGetRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.IconFontBitmapGetRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .wbapi.IconFontBitmapType type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // uint32 code = 2;
  if (this->code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->code(), output);
  }

  // int32 device_id = 3;
  if (this->device_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->device_id(), output);
  }

  // int32 sub_id = 4;
  if (this->sub_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->sub_id(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.IconFontBitmapGetRequest)
}

size_t IconFontBitmapGetRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.IconFontBitmapGetRequest)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // .wbapi.IconFontBitmapType type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  // uint32 code = 2;
  if (this->code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->code());
  }

  // int32 device_id = 3;
  if (this->device_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->device_id());
  }

  // int32 sub_id = 4;
  if (this->sub_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->sub_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void IconFontBitmapGetRequest::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const IconFontBitmapGetRequest*>(&from));
}

void IconFontBitmapGetRequest::MergeFrom(const IconFontBitmapGetRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.IconFontBitmapGetRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.code() != 0) {
    set_code(from.code());
  }
  if (from.device_id() != 0) {
    set_device_id(from.device_id());
  }
  if (from.sub_id() != 0) {
    set_sub_id(from.sub_id());
  }
}

void IconFontBitmapGetRequest::CopyFrom(const IconFontBitmapGetRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.IconFontBitmapGetRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IconFontBitmapGetRequest::IsInitialized() const {
  return true;
}

void IconFontBitmapGetRequest::Swap(IconFontBitmapGetRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void IconFontBitmapGetRequest::InternalSwap(IconFontBitmapGetRequest* other) {
  using std::swap;
  swap(type_, other->type_);
  swap(code_, other->code_);
  swap(device_id_, other->device_id_);
  swap(sub_id_, other->sub_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string IconFontBitmapGetRequest::GetTypeName() const {
  return "wbapi.IconFontBitmapGetRequest";
}


// ===================================================================

void IconFontBitmapGetResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int IconFontBitmapGetResponse::kErrorCodeFieldNumber;
const int IconFontBitmapGetResponse::kTypeFieldNumber;
const int IconFontBitmapGetResponse::kCodeFieldNumber;
const int IconFontBitmapGetResponse::kSectionFieldNumber;
const int IconFontBitmapGetResponse::kIndexFieldNumber;
const int IconFontBitmapGetResponse::kBitmapFieldNumber;
const int IconFontBitmapGetResponse::kDeviceIdFieldNumber;
const int IconFontBitmapGetResponse::kSubIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

IconFontBitmapGetResponse::IconFontBitmapGetResponse()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_hfonts_2eproto::scc_info_IconFontBitmapGetResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.IconFontBitmapGetResponse)
}
IconFontBitmapGetResponse::IconFontBitmapGetResponse(const IconFontBitmapGetResponse& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  bitmap_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.bitmap().size() > 0) {
    bitmap_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bitmap_);
  }
  ::memcpy(&error_code_, &from.error_code_,
    static_cast<size_t>(reinterpret_cast<char*>(&sub_id_) -
    reinterpret_cast<char*>(&error_code_)) + sizeof(sub_id_));
  // @@protoc_insertion_point(copy_constructor:wbapi.IconFontBitmapGetResponse)
}

void IconFontBitmapGetResponse::SharedCtor() {
  bitmap_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&error_code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sub_id_) -
      reinterpret_cast<char*>(&error_code_)) + sizeof(sub_id_));
}

IconFontBitmapGetResponse::~IconFontBitmapGetResponse() {
  // @@protoc_insertion_point(destructor:wbapi.IconFontBitmapGetResponse)
  SharedDtor();
}

void IconFontBitmapGetResponse::SharedDtor() {
  bitmap_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void IconFontBitmapGetResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const IconFontBitmapGetResponse& IconFontBitmapGetResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_hfonts_2eproto::scc_info_IconFontBitmapGetResponse.base);
  return *internal_default_instance();
}


void IconFontBitmapGetResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.IconFontBitmapGetResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  bitmap_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&error_code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sub_id_) -
      reinterpret_cast<char*>(&error_code_)) + sizeof(sub_id_));
  _internal_metadata_.Clear();
}

bool IconFontBitmapGetResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.IconFontBitmapGetResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 error_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .wbapi.IconFontBitmapType type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::wbapi::IconFontBitmapType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 code = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 section = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &section_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 index = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &index_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes bitmap = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_bitmap()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 device_id = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &device_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 sub_id = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sub_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.IconFontBitmapGetResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.IconFontBitmapGetResponse)
  return false;
#undef DO_
}

void IconFontBitmapGetResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.IconFontBitmapGetResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error_code(), output);
  }

  // .wbapi.IconFontBitmapType type = 2;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->type(), output);
  }

  // uint32 code = 3;
  if (this->code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->code(), output);
  }

  // uint32 section = 4;
  if (this->section() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->section(), output);
  }

  // uint32 index = 5;
  if (this->index() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->index(), output);
  }

  // bytes bitmap = 6;
  if (this->bitmap().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      6, this->bitmap(), output);
  }

  // int32 device_id = 7;
  if (this->device_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->device_id(), output);
  }

  // int32 sub_id = 8;
  if (this->sub_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->sub_id(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.IconFontBitmapGetResponse)
}

size_t IconFontBitmapGetResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.IconFontBitmapGetResponse)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // bytes bitmap = 6;
  if (this->bitmap().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->bitmap());
  }

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error_code());
  }

  // .wbapi.IconFontBitmapType type = 2;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  // uint32 code = 3;
  if (this->code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->code());
  }

  // uint32 section = 4;
  if (this->section() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->section());
  }

  // uint32 index = 5;
  if (this->index() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->index());
  }

  // int32 device_id = 7;
  if (this->device_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->device_id());
  }

  // int32 sub_id = 8;
  if (this->sub_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->sub_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void IconFontBitmapGetResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const IconFontBitmapGetResponse*>(&from));
}

void IconFontBitmapGetResponse::MergeFrom(const IconFontBitmapGetResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.IconFontBitmapGetResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.bitmap().size() > 0) {

    bitmap_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bitmap_);
  }
  if (from.error_code() != 0) {
    set_error_code(from.error_code());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.code() != 0) {
    set_code(from.code());
  }
  if (from.section() != 0) {
    set_section(from.section());
  }
  if (from.index() != 0) {
    set_index(from.index());
  }
  if (from.device_id() != 0) {
    set_device_id(from.device_id());
  }
  if (from.sub_id() != 0) {
    set_sub_id(from.sub_id());
  }
}

void IconFontBitmapGetResponse::CopyFrom(const IconFontBitmapGetResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.IconFontBitmapGetResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IconFontBitmapGetResponse::IsInitialized() const {
  return true;
}

void IconFontBitmapGetResponse::Swap(IconFontBitmapGetResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void IconFontBitmapGetResponse::InternalSwap(IconFontBitmapGetResponse* other) {
  using std::swap;
  bitmap_.Swap(&other->bitmap_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(error_code_, other->error_code_);
  swap(type_, other->type_);
  swap(code_, other->code_);
  swap(section_, other->section_);
  swap(index_, other->index_);
  swap(device_id_, other->device_id_);
  swap(sub_id_, other->sub_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string IconFontBitmapGetResponse::GetTypeName() const {
  return "wbapi.IconFontBitmapGetResponse";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace wbapi
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::IconFontBitmapGetRequest* Arena::CreateMaybeMessage< ::wbapi::IconFontBitmapGetRequest >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::IconFontBitmapGetRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::IconFontBitmapGetResponse* Arena::CreateMaybeMessage< ::wbapi::IconFontBitmapGetResponse >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::IconFontBitmapGetResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
