// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

#ifndef PROTOBUF_INCLUDED_login_2eproto
#define PROTOBUF_INCLUDED_login_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry_lite.h>
#include <google/protobuf/map_field_lite.h>
#include "basic.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_login_2eproto 

namespace protobuf_login_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[9];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
}  // namespace protobuf_login_2eproto
namespace wbapi {
class Ack;
class AckDefaultTypeInternal;
extern AckDefaultTypeInternal _Ack_default_instance_;
class AuthTokenRequest;
class AuthTokenRequestDefaultTypeInternal;
extern AuthTokenRequestDefaultTypeInternal _AuthTokenRequest_default_instance_;
class AuthTokenRequest_NetInfosEntry_DoNotUse;
class AuthTokenRequest_NetInfosEntry_DoNotUseDefaultTypeInternal;
extern AuthTokenRequest_NetInfosEntry_DoNotUseDefaultTypeInternal _AuthTokenRequest_NetInfosEntry_DoNotUse_default_instance_;
class AuthTokenResponse;
class AuthTokenResponseDefaultTypeInternal;
extern AuthTokenResponseDefaultTypeInternal _AuthTokenResponse_default_instance_;
class KickUserNotification;
class KickUserNotificationDefaultTypeInternal;
extern KickUserNotificationDefaultTypeInternal _KickUserNotification_default_instance_;
class LogoutRequest;
class LogoutRequestDefaultTypeInternal;
extern LogoutRequestDefaultTypeInternal _LogoutRequest_default_instance_;
class LogoutResponse;
class LogoutResponseDefaultTypeInternal;
extern LogoutResponseDefaultTypeInternal _LogoutResponse_default_instance_;
class Ping;
class PingDefaultTypeInternal;
extern PingDefaultTypeInternal _Ping_default_instance_;
class Pong;
class PongDefaultTypeInternal;
extern PongDefaultTypeInternal _Pong_default_instance_;
}  // namespace wbapi
namespace google {
namespace protobuf {
template<> ::wbapi::Ack* Arena::CreateMaybeMessage<::wbapi::Ack>(Arena*);
template<> ::wbapi::AuthTokenRequest* Arena::CreateMaybeMessage<::wbapi::AuthTokenRequest>(Arena*);
template<> ::wbapi::AuthTokenRequest_NetInfosEntry_DoNotUse* Arena::CreateMaybeMessage<::wbapi::AuthTokenRequest_NetInfosEntry_DoNotUse>(Arena*);
template<> ::wbapi::AuthTokenResponse* Arena::CreateMaybeMessage<::wbapi::AuthTokenResponse>(Arena*);
template<> ::wbapi::KickUserNotification* Arena::CreateMaybeMessage<::wbapi::KickUserNotification>(Arena*);
template<> ::wbapi::LogoutRequest* Arena::CreateMaybeMessage<::wbapi::LogoutRequest>(Arena*);
template<> ::wbapi::LogoutResponse* Arena::CreateMaybeMessage<::wbapi::LogoutResponse>(Arena*);
template<> ::wbapi::Ping* Arena::CreateMaybeMessage<::wbapi::Ping>(Arena*);
template<> ::wbapi::Pong* Arena::CreateMaybeMessage<::wbapi::Pong>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace wbapi {

// ===================================================================

class AuthTokenRequest_NetInfosEntry_DoNotUse : public ::google::protobuf::internal::MapEntryLite<AuthTokenRequest_NetInfosEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntryLite<AuthTokenRequest_NetInfosEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  AuthTokenRequest_NetInfosEntry_DoNotUse();
  AuthTokenRequest_NetInfosEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const AuthTokenRequest_NetInfosEntry_DoNotUse& other);
  static const AuthTokenRequest_NetInfosEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const AuthTokenRequest_NetInfosEntry_DoNotUse*>(&_AuthTokenRequest_NetInfosEntry_DoNotUse_default_instance_); }
};

// -------------------------------------------------------------------

class AuthTokenRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.AuthTokenRequest) */ {
 public:
  AuthTokenRequest();
  virtual ~AuthTokenRequest();

  AuthTokenRequest(const AuthTokenRequest& from);

  inline AuthTokenRequest& operator=(const AuthTokenRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AuthTokenRequest(AuthTokenRequest&& from) noexcept
    : AuthTokenRequest() {
    *this = ::std::move(from);
  }

  inline AuthTokenRequest& operator=(AuthTokenRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const AuthTokenRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AuthTokenRequest* internal_default_instance() {
    return reinterpret_cast<const AuthTokenRequest*>(
               &_AuthTokenRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(AuthTokenRequest* other);
  friend void swap(AuthTokenRequest& a, AuthTokenRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AuthTokenRequest* New() const final {
    return CreateMaybeMessage<AuthTokenRequest>(NULL);
  }

  AuthTokenRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AuthTokenRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const AuthTokenRequest& from);
  void MergeFrom(const AuthTokenRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AuthTokenRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> net_infos = 11;
  int net_infos_size() const;
  void clear_net_infos();
  static const int kNetInfosFieldNumber = 11;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      net_infos() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_net_infos();

  // string soft_version = 6;
  void clear_soft_version();
  static const int kSoftVersionFieldNumber = 6;
  const ::std::string& soft_version() const;
  void set_soft_version(const ::std::string& value);
  #if LANG_CXX11
  void set_soft_version(::std::string&& value);
  #endif
  void set_soft_version(const char* value);
  void set_soft_version(const char* value, size_t size);
  ::std::string* mutable_soft_version();
  ::std::string* release_soft_version();
  void set_allocated_soft_version(::std::string* soft_version);

  // string hard_version = 7;
  void clear_hard_version();
  static const int kHardVersionFieldNumber = 7;
  const ::std::string& hard_version() const;
  void set_hard_version(const ::std::string& value);
  #if LANG_CXX11
  void set_hard_version(::std::string&& value);
  #endif
  void set_hard_version(const char* value);
  void set_hard_version(const char* value, size_t size);
  ::std::string* mutable_hard_version();
  ::std::string* release_hard_version();
  void set_allocated_hard_version(::std::string* hard_version);

  // string access_token = 8;
  void clear_access_token();
  static const int kAccessTokenFieldNumber = 8;
  const ::std::string& access_token() const;
  void set_access_token(const ::std::string& value);
  #if LANG_CXX11
  void set_access_token(::std::string&& value);
  #endif
  void set_access_token(const char* value);
  void set_access_token(const char* value, size_t size);
  ::std::string* mutable_access_token();
  ::std::string* release_access_token();
  void set_allocated_access_token(::std::string* access_token);

  // string model = 9;
  void clear_model();
  static const int kModelFieldNumber = 9;
  const ::std::string& model() const;
  void set_model(const ::std::string& value);
  #if LANG_CXX11
  void set_model(::std::string&& value);
  #endif
  void set_model(const char* value);
  void set_model(const char* value, size_t size);
  ::std::string* mutable_model();
  ::std::string* release_model();
  void set_allocated_model(::std::string* model);

  // string device_id = 10;
  void clear_device_id();
  static const int kDeviceIdFieldNumber = 10;
  const ::std::string& device_id() const;
  void set_device_id(const ::std::string& value);
  #if LANG_CXX11
  void set_device_id(::std::string&& value);
  #endif
  void set_device_id(const char* value);
  void set_device_id(const char* value, size_t size);
  ::std::string* mutable_device_id();
  ::std::string* release_device_id();
  void set_allocated_device_id(::std::string* device_id);

  // int64 appid = 1;
  void clear_appid();
  static const int kAppidFieldNumber = 1;
  ::google::protobuf::int64 appid() const;
  void set_appid(::google::protobuf::int64 value);

  // int64 uid = 2;
  void clear_uid();
  static const int kUidFieldNumber = 2;
  ::google::protobuf::int64 uid() const;
  void set_uid(::google::protobuf::int64 value);

  // int32 client_type = 3;
  void clear_client_type();
  static const int kClientTypeFieldNumber = 3;
  ::google::protobuf::int32 client_type() const;
  void set_client_type(::google::protobuf::int32 value);

  // int32 platform = 4;
  void clear_platform();
  static const int kPlatformFieldNumber = 4;
  ::google::protobuf::int32 platform() const;
  void set_platform(::google::protobuf::int32 value);

  // int32 soft_type = 5;
  void clear_soft_type();
  static const int kSoftTypeFieldNumber = 5;
  ::google::protobuf::int32 soft_type() const;
  void set_soft_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wbapi.AuthTokenRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::MapFieldLite<
      AuthTokenRequest_NetInfosEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > net_infos_;
  ::google::protobuf::internal::ArenaStringPtr soft_version_;
  ::google::protobuf::internal::ArenaStringPtr hard_version_;
  ::google::protobuf::internal::ArenaStringPtr access_token_;
  ::google::protobuf::internal::ArenaStringPtr model_;
  ::google::protobuf::internal::ArenaStringPtr device_id_;
  ::google::protobuf::int64 appid_;
  ::google::protobuf::int64 uid_;
  ::google::protobuf::int32 client_type_;
  ::google::protobuf::int32 platform_;
  ::google::protobuf::int32 soft_type_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_login_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AuthTokenResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.AuthTokenResponse) */ {
 public:
  AuthTokenResponse();
  virtual ~AuthTokenResponse();

  AuthTokenResponse(const AuthTokenResponse& from);

  inline AuthTokenResponse& operator=(const AuthTokenResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AuthTokenResponse(AuthTokenResponse&& from) noexcept
    : AuthTokenResponse() {
    *this = ::std::move(from);
  }

  inline AuthTokenResponse& operator=(AuthTokenResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const AuthTokenResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AuthTokenResponse* internal_default_instance() {
    return reinterpret_cast<const AuthTokenResponse*>(
               &_AuthTokenResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(AuthTokenResponse* other);
  friend void swap(AuthTokenResponse& a, AuthTokenResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AuthTokenResponse* New() const final {
    return CreateMaybeMessage<AuthTokenResponse>(NULL);
  }

  AuthTokenResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AuthTokenResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const AuthTokenResponse& from);
  void MergeFrom(const AuthTokenResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AuthTokenResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string family_name = 4;
  void clear_family_name();
  static const int kFamilyNameFieldNumber = 4;
  const ::std::string& family_name() const;
  void set_family_name(const ::std::string& value);
  #if LANG_CXX11
  void set_family_name(::std::string&& value);
  #endif
  void set_family_name(const char* value);
  void set_family_name(const char* value, size_t size);
  ::std::string* mutable_family_name();
  ::std::string* release_family_name();
  void set_allocated_family_name(::std::string* family_name);

  // int32 error_code = 1;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 error_code() const;
  void set_error_code(::google::protobuf::int32 value);

  // int32 idle_time = 2;
  void clear_idle_time();
  static const int kIdleTimeFieldNumber = 2;
  ::google::protobuf::int32 idle_time() const;
  void set_idle_time(::google::protobuf::int32 value);

  // int32 family_id = 3;
  void clear_family_id();
  static const int kFamilyIdFieldNumber = 3;
  ::google::protobuf::int32 family_id() const;
  void set_family_id(::google::protobuf::int32 value);

  // int32 family_member_type = 5;
  void clear_family_member_type();
  static const int kFamilyMemberTypeFieldNumber = 5;
  ::google::protobuf::int32 family_member_type() const;
  void set_family_member_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wbapi.AuthTokenResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr family_name_;
  ::google::protobuf::int32 error_code_;
  ::google::protobuf::int32 idle_time_;
  ::google::protobuf::int32 family_id_;
  ::google::protobuf::int32 family_member_type_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_login_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Ping : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.Ping) */ {
 public:
  Ping();
  virtual ~Ping();

  Ping(const Ping& from);

  inline Ping& operator=(const Ping& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Ping(Ping&& from) noexcept
    : Ping() {
    *this = ::std::move(from);
  }

  inline Ping& operator=(Ping&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const Ping& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Ping* internal_default_instance() {
    return reinterpret_cast<const Ping*>(
               &_Ping_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(Ping* other);
  friend void swap(Ping& a, Ping& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Ping* New() const final {
    return CreateMaybeMessage<Ping>(NULL);
  }

  Ping* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Ping>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const Ping& from);
  void MergeFrom(const Ping& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Ping* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::int32 timestamp() const;
  void set_timestamp(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wbapi.Ping)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::int32 timestamp_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_login_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Pong : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.Pong) */ {
 public:
  Pong();
  virtual ~Pong();

  Pong(const Pong& from);

  inline Pong& operator=(const Pong& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Pong(Pong&& from) noexcept
    : Pong() {
    *this = ::std::move(from);
  }

  inline Pong& operator=(Pong&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const Pong& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Pong* internal_default_instance() {
    return reinterpret_cast<const Pong*>(
               &_Pong_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(Pong* other);
  friend void swap(Pong& a, Pong& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Pong* New() const final {
    return CreateMaybeMessage<Pong>(NULL);
  }

  Pong* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Pong>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const Pong& from);
  void MergeFrom(const Pong& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Pong* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::int32 timestamp() const;
  void set_timestamp(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wbapi.Pong)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::int32 timestamp_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_login_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Ack : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.Ack) */ {
 public:
  Ack();
  virtual ~Ack();

  Ack(const Ack& from);

  inline Ack& operator=(const Ack& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Ack(Ack&& from) noexcept
    : Ack() {
    *this = ::std::move(from);
  }

  inline Ack& operator=(Ack&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const Ack& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Ack* internal_default_instance() {
    return reinterpret_cast<const Ack*>(
               &_Ack_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(Ack* other);
  friend void swap(Ack& a, Ack& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Ack* New() const final {
    return CreateMaybeMessage<Ack>(NULL);
  }

  Ack* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Ack>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const Ack& from);
  void MergeFrom(const Ack& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Ack* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 seq_nos = 1;
  int seq_nos_size() const;
  void clear_seq_nos();
  static const int kSeqNosFieldNumber = 1;
  ::google::protobuf::int32 seq_nos(int index) const;
  void set_seq_nos(int index, ::google::protobuf::int32 value);
  void add_seq_nos(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      seq_nos() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_seq_nos();

  // @@protoc_insertion_point(class_scope:wbapi.Ack)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > seq_nos_;
  mutable int _seq_nos_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_login_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class KickUserNotification : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.KickUserNotification) */ {
 public:
  KickUserNotification();
  virtual ~KickUserNotification();

  KickUserNotification(const KickUserNotification& from);

  inline KickUserNotification& operator=(const KickUserNotification& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  KickUserNotification(KickUserNotification&& from) noexcept
    : KickUserNotification() {
    *this = ::std::move(from);
  }

  inline KickUserNotification& operator=(KickUserNotification&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const KickUserNotification& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const KickUserNotification* internal_default_instance() {
    return reinterpret_cast<const KickUserNotification*>(
               &_KickUserNotification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(KickUserNotification* other);
  friend void swap(KickUserNotification& a, KickUserNotification& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline KickUserNotification* New() const final {
    return CreateMaybeMessage<KickUserNotification>(NULL);
  }

  KickUserNotification* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<KickUserNotification>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const KickUserNotification& from);
  void MergeFrom(const KickUserNotification& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(KickUserNotification* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string model = 4;
  void clear_model();
  static const int kModelFieldNumber = 4;
  const ::std::string& model() const;
  void set_model(const ::std::string& value);
  #if LANG_CXX11
  void set_model(::std::string&& value);
  #endif
  void set_model(const char* value);
  void set_model(const char* value, size_t size);
  ::std::string* mutable_model();
  ::std::string* release_model();
  void set_allocated_model(::std::string* model);

  // int64 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::int64 user_id() const;
  void set_user_id(::google::protobuf::int64 value);

  // .wbapi.KickUserReason reason = 2;
  void clear_reason();
  static const int kReasonFieldNumber = 2;
  ::wbapi::KickUserReason reason() const;
  void set_reason(::wbapi::KickUserReason value);

  // int32 platform = 3;
  void clear_platform();
  static const int kPlatformFieldNumber = 3;
  ::google::protobuf::int32 platform() const;
  void set_platform(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wbapi.KickUserNotification)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr model_;
  ::google::protobuf::int64 user_id_;
  int reason_;
  ::google::protobuf::int32 platform_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_login_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LogoutRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.LogoutRequest) */ {
 public:
  LogoutRequest();
  virtual ~LogoutRequest();

  LogoutRequest(const LogoutRequest& from);

  inline LogoutRequest& operator=(const LogoutRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LogoutRequest(LogoutRequest&& from) noexcept
    : LogoutRequest() {
    *this = ::std::move(from);
  }

  inline LogoutRequest& operator=(LogoutRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const LogoutRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogoutRequest* internal_default_instance() {
    return reinterpret_cast<const LogoutRequest*>(
               &_LogoutRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(LogoutRequest* other);
  friend void swap(LogoutRequest& a, LogoutRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LogoutRequest* New() const final {
    return CreateMaybeMessage<LogoutRequest>(NULL);
  }

  LogoutRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LogoutRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const LogoutRequest& from);
  void MergeFrom(const LogoutRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LogoutRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool cancel_push = 1;
  void clear_cancel_push();
  static const int kCancelPushFieldNumber = 1;
  bool cancel_push() const;
  void set_cancel_push(bool value);

  // int32 platform = 2;
  void clear_platform();
  static const int kPlatformFieldNumber = 2;
  ::google::protobuf::int32 platform() const;
  void set_platform(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wbapi.LogoutRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  bool cancel_push_;
  ::google::protobuf::int32 platform_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_login_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LogoutResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.LogoutResponse) */ {
 public:
  LogoutResponse();
  virtual ~LogoutResponse();

  LogoutResponse(const LogoutResponse& from);

  inline LogoutResponse& operator=(const LogoutResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LogoutResponse(LogoutResponse&& from) noexcept
    : LogoutResponse() {
    *this = ::std::move(from);
  }

  inline LogoutResponse& operator=(LogoutResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const LogoutResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogoutResponse* internal_default_instance() {
    return reinterpret_cast<const LogoutResponse*>(
               &_LogoutResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(LogoutResponse* other);
  friend void swap(LogoutResponse& a, LogoutResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LogoutResponse* New() const final {
    return CreateMaybeMessage<LogoutResponse>(NULL);
  }

  LogoutResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LogoutResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const LogoutResponse& from);
  void MergeFrom(const LogoutResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LogoutResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 error_code = 1;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 error_code() const;
  void set_error_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wbapi.LogoutResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::int32 error_code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_login_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AuthTokenRequest

// int64 appid = 1;
inline void AuthTokenRequest::clear_appid() {
  appid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 AuthTokenRequest::appid() const {
  // @@protoc_insertion_point(field_get:wbapi.AuthTokenRequest.appid)
  return appid_;
}
inline void AuthTokenRequest::set_appid(::google::protobuf::int64 value) {
  
  appid_ = value;
  // @@protoc_insertion_point(field_set:wbapi.AuthTokenRequest.appid)
}

// int64 uid = 2;
inline void AuthTokenRequest::clear_uid() {
  uid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 AuthTokenRequest::uid() const {
  // @@protoc_insertion_point(field_get:wbapi.AuthTokenRequest.uid)
  return uid_;
}
inline void AuthTokenRequest::set_uid(::google::protobuf::int64 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:wbapi.AuthTokenRequest.uid)
}

// int32 client_type = 3;
inline void AuthTokenRequest::clear_client_type() {
  client_type_ = 0;
}
inline ::google::protobuf::int32 AuthTokenRequest::client_type() const {
  // @@protoc_insertion_point(field_get:wbapi.AuthTokenRequest.client_type)
  return client_type_;
}
inline void AuthTokenRequest::set_client_type(::google::protobuf::int32 value) {
  
  client_type_ = value;
  // @@protoc_insertion_point(field_set:wbapi.AuthTokenRequest.client_type)
}

// int32 platform = 4;
inline void AuthTokenRequest::clear_platform() {
  platform_ = 0;
}
inline ::google::protobuf::int32 AuthTokenRequest::platform() const {
  // @@protoc_insertion_point(field_get:wbapi.AuthTokenRequest.platform)
  return platform_;
}
inline void AuthTokenRequest::set_platform(::google::protobuf::int32 value) {
  
  platform_ = value;
  // @@protoc_insertion_point(field_set:wbapi.AuthTokenRequest.platform)
}

// int32 soft_type = 5;
inline void AuthTokenRequest::clear_soft_type() {
  soft_type_ = 0;
}
inline ::google::protobuf::int32 AuthTokenRequest::soft_type() const {
  // @@protoc_insertion_point(field_get:wbapi.AuthTokenRequest.soft_type)
  return soft_type_;
}
inline void AuthTokenRequest::set_soft_type(::google::protobuf::int32 value) {
  
  soft_type_ = value;
  // @@protoc_insertion_point(field_set:wbapi.AuthTokenRequest.soft_type)
}

// string soft_version = 6;
inline void AuthTokenRequest::clear_soft_version() {
  soft_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AuthTokenRequest::soft_version() const {
  // @@protoc_insertion_point(field_get:wbapi.AuthTokenRequest.soft_version)
  return soft_version_.GetNoArena();
}
inline void AuthTokenRequest::set_soft_version(const ::std::string& value) {
  
  soft_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:wbapi.AuthTokenRequest.soft_version)
}
#if LANG_CXX11
inline void AuthTokenRequest::set_soft_version(::std::string&& value) {
  
  soft_version_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:wbapi.AuthTokenRequest.soft_version)
}
#endif
inline void AuthTokenRequest::set_soft_version(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  soft_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:wbapi.AuthTokenRequest.soft_version)
}
inline void AuthTokenRequest::set_soft_version(const char* value, size_t size) {
  
  soft_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:wbapi.AuthTokenRequest.soft_version)
}
inline ::std::string* AuthTokenRequest::mutable_soft_version() {
  
  // @@protoc_insertion_point(field_mutable:wbapi.AuthTokenRequest.soft_version)
  return soft_version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AuthTokenRequest::release_soft_version() {
  // @@protoc_insertion_point(field_release:wbapi.AuthTokenRequest.soft_version)
  
  return soft_version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AuthTokenRequest::set_allocated_soft_version(::std::string* soft_version) {
  if (soft_version != NULL) {
    
  } else {
    
  }
  soft_version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), soft_version);
  // @@protoc_insertion_point(field_set_allocated:wbapi.AuthTokenRequest.soft_version)
}

// string hard_version = 7;
inline void AuthTokenRequest::clear_hard_version() {
  hard_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AuthTokenRequest::hard_version() const {
  // @@protoc_insertion_point(field_get:wbapi.AuthTokenRequest.hard_version)
  return hard_version_.GetNoArena();
}
inline void AuthTokenRequest::set_hard_version(const ::std::string& value) {
  
  hard_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:wbapi.AuthTokenRequest.hard_version)
}
#if LANG_CXX11
inline void AuthTokenRequest::set_hard_version(::std::string&& value) {
  
  hard_version_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:wbapi.AuthTokenRequest.hard_version)
}
#endif
inline void AuthTokenRequest::set_hard_version(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  hard_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:wbapi.AuthTokenRequest.hard_version)
}
inline void AuthTokenRequest::set_hard_version(const char* value, size_t size) {
  
  hard_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:wbapi.AuthTokenRequest.hard_version)
}
inline ::std::string* AuthTokenRequest::mutable_hard_version() {
  
  // @@protoc_insertion_point(field_mutable:wbapi.AuthTokenRequest.hard_version)
  return hard_version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AuthTokenRequest::release_hard_version() {
  // @@protoc_insertion_point(field_release:wbapi.AuthTokenRequest.hard_version)
  
  return hard_version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AuthTokenRequest::set_allocated_hard_version(::std::string* hard_version) {
  if (hard_version != NULL) {
    
  } else {
    
  }
  hard_version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hard_version);
  // @@protoc_insertion_point(field_set_allocated:wbapi.AuthTokenRequest.hard_version)
}

// string access_token = 8;
inline void AuthTokenRequest::clear_access_token() {
  access_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AuthTokenRequest::access_token() const {
  // @@protoc_insertion_point(field_get:wbapi.AuthTokenRequest.access_token)
  return access_token_.GetNoArena();
}
inline void AuthTokenRequest::set_access_token(const ::std::string& value) {
  
  access_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:wbapi.AuthTokenRequest.access_token)
}
#if LANG_CXX11
inline void AuthTokenRequest::set_access_token(::std::string&& value) {
  
  access_token_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:wbapi.AuthTokenRequest.access_token)
}
#endif
inline void AuthTokenRequest::set_access_token(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  access_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:wbapi.AuthTokenRequest.access_token)
}
inline void AuthTokenRequest::set_access_token(const char* value, size_t size) {
  
  access_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:wbapi.AuthTokenRequest.access_token)
}
inline ::std::string* AuthTokenRequest::mutable_access_token() {
  
  // @@protoc_insertion_point(field_mutable:wbapi.AuthTokenRequest.access_token)
  return access_token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AuthTokenRequest::release_access_token() {
  // @@protoc_insertion_point(field_release:wbapi.AuthTokenRequest.access_token)
  
  return access_token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AuthTokenRequest::set_allocated_access_token(::std::string* access_token) {
  if (access_token != NULL) {
    
  } else {
    
  }
  access_token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), access_token);
  // @@protoc_insertion_point(field_set_allocated:wbapi.AuthTokenRequest.access_token)
}

// string model = 9;
inline void AuthTokenRequest::clear_model() {
  model_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AuthTokenRequest::model() const {
  // @@protoc_insertion_point(field_get:wbapi.AuthTokenRequest.model)
  return model_.GetNoArena();
}
inline void AuthTokenRequest::set_model(const ::std::string& value) {
  
  model_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:wbapi.AuthTokenRequest.model)
}
#if LANG_CXX11
inline void AuthTokenRequest::set_model(::std::string&& value) {
  
  model_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:wbapi.AuthTokenRequest.model)
}
#endif
inline void AuthTokenRequest::set_model(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  model_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:wbapi.AuthTokenRequest.model)
}
inline void AuthTokenRequest::set_model(const char* value, size_t size) {
  
  model_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:wbapi.AuthTokenRequest.model)
}
inline ::std::string* AuthTokenRequest::mutable_model() {
  
  // @@protoc_insertion_point(field_mutable:wbapi.AuthTokenRequest.model)
  return model_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AuthTokenRequest::release_model() {
  // @@protoc_insertion_point(field_release:wbapi.AuthTokenRequest.model)
  
  return model_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AuthTokenRequest::set_allocated_model(::std::string* model) {
  if (model != NULL) {
    
  } else {
    
  }
  model_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), model);
  // @@protoc_insertion_point(field_set_allocated:wbapi.AuthTokenRequest.model)
}

// string device_id = 10;
inline void AuthTokenRequest::clear_device_id() {
  device_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AuthTokenRequest::device_id() const {
  // @@protoc_insertion_point(field_get:wbapi.AuthTokenRequest.device_id)
  return device_id_.GetNoArena();
}
inline void AuthTokenRequest::set_device_id(const ::std::string& value) {
  
  device_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:wbapi.AuthTokenRequest.device_id)
}
#if LANG_CXX11
inline void AuthTokenRequest::set_device_id(::std::string&& value) {
  
  device_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:wbapi.AuthTokenRequest.device_id)
}
#endif
inline void AuthTokenRequest::set_device_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  device_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:wbapi.AuthTokenRequest.device_id)
}
inline void AuthTokenRequest::set_device_id(const char* value, size_t size) {
  
  device_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:wbapi.AuthTokenRequest.device_id)
}
inline ::std::string* AuthTokenRequest::mutable_device_id() {
  
  // @@protoc_insertion_point(field_mutable:wbapi.AuthTokenRequest.device_id)
  return device_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AuthTokenRequest::release_device_id() {
  // @@protoc_insertion_point(field_release:wbapi.AuthTokenRequest.device_id)
  
  return device_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AuthTokenRequest::set_allocated_device_id(::std::string* device_id) {
  if (device_id != NULL) {
    
  } else {
    
  }
  device_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_id);
  // @@protoc_insertion_point(field_set_allocated:wbapi.AuthTokenRequest.device_id)
}

// map<string, string> net_infos = 11;
inline int AuthTokenRequest::net_infos_size() const {
  return net_infos_.size();
}
inline void AuthTokenRequest::clear_net_infos() {
  net_infos_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
AuthTokenRequest::net_infos() const {
  // @@protoc_insertion_point(field_map:wbapi.AuthTokenRequest.net_infos)
  return net_infos_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
AuthTokenRequest::mutable_net_infos() {
  // @@protoc_insertion_point(field_mutable_map:wbapi.AuthTokenRequest.net_infos)
  return net_infos_.MutableMap();
}

// -------------------------------------------------------------------

// AuthTokenResponse

// int32 error_code = 1;
inline void AuthTokenResponse::clear_error_code() {
  error_code_ = 0;
}
inline ::google::protobuf::int32 AuthTokenResponse::error_code() const {
  // @@protoc_insertion_point(field_get:wbapi.AuthTokenResponse.error_code)
  return error_code_;
}
inline void AuthTokenResponse::set_error_code(::google::protobuf::int32 value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:wbapi.AuthTokenResponse.error_code)
}

// int32 idle_time = 2;
inline void AuthTokenResponse::clear_idle_time() {
  idle_time_ = 0;
}
inline ::google::protobuf::int32 AuthTokenResponse::idle_time() const {
  // @@protoc_insertion_point(field_get:wbapi.AuthTokenResponse.idle_time)
  return idle_time_;
}
inline void AuthTokenResponse::set_idle_time(::google::protobuf::int32 value) {
  
  idle_time_ = value;
  // @@protoc_insertion_point(field_set:wbapi.AuthTokenResponse.idle_time)
}

// int32 family_id = 3;
inline void AuthTokenResponse::clear_family_id() {
  family_id_ = 0;
}
inline ::google::protobuf::int32 AuthTokenResponse::family_id() const {
  // @@protoc_insertion_point(field_get:wbapi.AuthTokenResponse.family_id)
  return family_id_;
}
inline void AuthTokenResponse::set_family_id(::google::protobuf::int32 value) {
  
  family_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.AuthTokenResponse.family_id)
}

// string family_name = 4;
inline void AuthTokenResponse::clear_family_name() {
  family_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AuthTokenResponse::family_name() const {
  // @@protoc_insertion_point(field_get:wbapi.AuthTokenResponse.family_name)
  return family_name_.GetNoArena();
}
inline void AuthTokenResponse::set_family_name(const ::std::string& value) {
  
  family_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:wbapi.AuthTokenResponse.family_name)
}
#if LANG_CXX11
inline void AuthTokenResponse::set_family_name(::std::string&& value) {
  
  family_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:wbapi.AuthTokenResponse.family_name)
}
#endif
inline void AuthTokenResponse::set_family_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  family_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:wbapi.AuthTokenResponse.family_name)
}
inline void AuthTokenResponse::set_family_name(const char* value, size_t size) {
  
  family_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:wbapi.AuthTokenResponse.family_name)
}
inline ::std::string* AuthTokenResponse::mutable_family_name() {
  
  // @@protoc_insertion_point(field_mutable:wbapi.AuthTokenResponse.family_name)
  return family_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AuthTokenResponse::release_family_name() {
  // @@protoc_insertion_point(field_release:wbapi.AuthTokenResponse.family_name)
  
  return family_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AuthTokenResponse::set_allocated_family_name(::std::string* family_name) {
  if (family_name != NULL) {
    
  } else {
    
  }
  family_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), family_name);
  // @@protoc_insertion_point(field_set_allocated:wbapi.AuthTokenResponse.family_name)
}

// int32 family_member_type = 5;
inline void AuthTokenResponse::clear_family_member_type() {
  family_member_type_ = 0;
}
inline ::google::protobuf::int32 AuthTokenResponse::family_member_type() const {
  // @@protoc_insertion_point(field_get:wbapi.AuthTokenResponse.family_member_type)
  return family_member_type_;
}
inline void AuthTokenResponse::set_family_member_type(::google::protobuf::int32 value) {
  
  family_member_type_ = value;
  // @@protoc_insertion_point(field_set:wbapi.AuthTokenResponse.family_member_type)
}

// -------------------------------------------------------------------

// Ping

// int32 timestamp = 1;
inline void Ping::clear_timestamp() {
  timestamp_ = 0;
}
inline ::google::protobuf::int32 Ping::timestamp() const {
  // @@protoc_insertion_point(field_get:wbapi.Ping.timestamp)
  return timestamp_;
}
inline void Ping::set_timestamp(::google::protobuf::int32 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:wbapi.Ping.timestamp)
}

// -------------------------------------------------------------------

// Pong

// int32 timestamp = 1;
inline void Pong::clear_timestamp() {
  timestamp_ = 0;
}
inline ::google::protobuf::int32 Pong::timestamp() const {
  // @@protoc_insertion_point(field_get:wbapi.Pong.timestamp)
  return timestamp_;
}
inline void Pong::set_timestamp(::google::protobuf::int32 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:wbapi.Pong.timestamp)
}

// -------------------------------------------------------------------

// Ack

// repeated int32 seq_nos = 1;
inline int Ack::seq_nos_size() const {
  return seq_nos_.size();
}
inline void Ack::clear_seq_nos() {
  seq_nos_.Clear();
}
inline ::google::protobuf::int32 Ack::seq_nos(int index) const {
  // @@protoc_insertion_point(field_get:wbapi.Ack.seq_nos)
  return seq_nos_.Get(index);
}
inline void Ack::set_seq_nos(int index, ::google::protobuf::int32 value) {
  seq_nos_.Set(index, value);
  // @@protoc_insertion_point(field_set:wbapi.Ack.seq_nos)
}
inline void Ack::add_seq_nos(::google::protobuf::int32 value) {
  seq_nos_.Add(value);
  // @@protoc_insertion_point(field_add:wbapi.Ack.seq_nos)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Ack::seq_nos() const {
  // @@protoc_insertion_point(field_list:wbapi.Ack.seq_nos)
  return seq_nos_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Ack::mutable_seq_nos() {
  // @@protoc_insertion_point(field_mutable_list:wbapi.Ack.seq_nos)
  return &seq_nos_;
}

// -------------------------------------------------------------------

// KickUserNotification

// int64 user_id = 1;
inline void KickUserNotification::clear_user_id() {
  user_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 KickUserNotification::user_id() const {
  // @@protoc_insertion_point(field_get:wbapi.KickUserNotification.user_id)
  return user_id_;
}
inline void KickUserNotification::set_user_id(::google::protobuf::int64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.KickUserNotification.user_id)
}

// .wbapi.KickUserReason reason = 2;
inline void KickUserNotification::clear_reason() {
  reason_ = 0;
}
inline ::wbapi::KickUserReason KickUserNotification::reason() const {
  // @@protoc_insertion_point(field_get:wbapi.KickUserNotification.reason)
  return static_cast< ::wbapi::KickUserReason >(reason_);
}
inline void KickUserNotification::set_reason(::wbapi::KickUserReason value) {
  
  reason_ = value;
  // @@protoc_insertion_point(field_set:wbapi.KickUserNotification.reason)
}

// int32 platform = 3;
inline void KickUserNotification::clear_platform() {
  platform_ = 0;
}
inline ::google::protobuf::int32 KickUserNotification::platform() const {
  // @@protoc_insertion_point(field_get:wbapi.KickUserNotification.platform)
  return platform_;
}
inline void KickUserNotification::set_platform(::google::protobuf::int32 value) {
  
  platform_ = value;
  // @@protoc_insertion_point(field_set:wbapi.KickUserNotification.platform)
}

// string model = 4;
inline void KickUserNotification::clear_model() {
  model_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& KickUserNotification::model() const {
  // @@protoc_insertion_point(field_get:wbapi.KickUserNotification.model)
  return model_.GetNoArena();
}
inline void KickUserNotification::set_model(const ::std::string& value) {
  
  model_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:wbapi.KickUserNotification.model)
}
#if LANG_CXX11
inline void KickUserNotification::set_model(::std::string&& value) {
  
  model_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:wbapi.KickUserNotification.model)
}
#endif
inline void KickUserNotification::set_model(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  model_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:wbapi.KickUserNotification.model)
}
inline void KickUserNotification::set_model(const char* value, size_t size) {
  
  model_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:wbapi.KickUserNotification.model)
}
inline ::std::string* KickUserNotification::mutable_model() {
  
  // @@protoc_insertion_point(field_mutable:wbapi.KickUserNotification.model)
  return model_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* KickUserNotification::release_model() {
  // @@protoc_insertion_point(field_release:wbapi.KickUserNotification.model)
  
  return model_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KickUserNotification::set_allocated_model(::std::string* model) {
  if (model != NULL) {
    
  } else {
    
  }
  model_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), model);
  // @@protoc_insertion_point(field_set_allocated:wbapi.KickUserNotification.model)
}

// -------------------------------------------------------------------

// LogoutRequest

// bool cancel_push = 1;
inline void LogoutRequest::clear_cancel_push() {
  cancel_push_ = false;
}
inline bool LogoutRequest::cancel_push() const {
  // @@protoc_insertion_point(field_get:wbapi.LogoutRequest.cancel_push)
  return cancel_push_;
}
inline void LogoutRequest::set_cancel_push(bool value) {
  
  cancel_push_ = value;
  // @@protoc_insertion_point(field_set:wbapi.LogoutRequest.cancel_push)
}

// int32 platform = 2;
inline void LogoutRequest::clear_platform() {
  platform_ = 0;
}
inline ::google::protobuf::int32 LogoutRequest::platform() const {
  // @@protoc_insertion_point(field_get:wbapi.LogoutRequest.platform)
  return platform_;
}
inline void LogoutRequest::set_platform(::google::protobuf::int32 value) {
  
  platform_ = value;
  // @@protoc_insertion_point(field_set:wbapi.LogoutRequest.platform)
}

// -------------------------------------------------------------------

// LogoutResponse

// int32 error_code = 1;
inline void LogoutResponse::clear_error_code() {
  error_code_ = 0;
}
inline ::google::protobuf::int32 LogoutResponse::error_code() const {
  // @@protoc_insertion_point(field_get:wbapi.LogoutResponse.error_code)
  return error_code_;
}
inline void LogoutResponse::set_error_code(::google::protobuf::int32 value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:wbapi.LogoutResponse.error_code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace wbapi

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_login_2eproto
