// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_unread.proto

#include "msg_unread.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_basic_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_basic_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_FamilyActionMsg;
}  // namespace protobuf_basic_2eproto
namespace protobuf_msg_5funread_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_msg_5funread_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_FamilyActionMsgTypeUnreadInfo;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_msg_5funread_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_FamilyActionMsgUnreadInfo;
}  // namespace protobuf_msg_5funread_2eproto
namespace wbapi {
class FamilyActionMsgTypeUnreadInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FamilyActionMsgTypeUnreadInfo>
      _instance;
} _FamilyActionMsgTypeUnreadInfo_default_instance_;
class FamilyActionMsgUnreadInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FamilyActionMsgUnreadInfo>
      _instance;
} _FamilyActionMsgUnreadInfo_default_instance_;
class SYSMsgUnreadCntRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SYSMsgUnreadCntRequest>
      _instance;
} _SYSMsgUnreadCntRequest_default_instance_;
class SYSMsgUnreadCntResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SYSMsgUnreadCntResponse>
      _instance;
} _SYSMsgUnreadCntResponse_default_instance_;
}  // namespace wbapi
namespace protobuf_msg_5funread_2eproto {
static void InitDefaultsFamilyActionMsgTypeUnreadInfo() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_FamilyActionMsgTypeUnreadInfo_default_instance_;
    new (ptr) ::wbapi::FamilyActionMsgTypeUnreadInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::FamilyActionMsgTypeUnreadInfo::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_FamilyActionMsgTypeUnreadInfo =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsFamilyActionMsgTypeUnreadInfo}, {
      &protobuf_basic_2eproto::scc_info_FamilyActionMsg.base,}};

static void InitDefaultsFamilyActionMsgUnreadInfo() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_FamilyActionMsgUnreadInfo_default_instance_;
    new (ptr) ::wbapi::FamilyActionMsgUnreadInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::FamilyActionMsgUnreadInfo::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_FamilyActionMsgUnreadInfo =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsFamilyActionMsgUnreadInfo}, {
      &protobuf_msg_5funread_2eproto::scc_info_FamilyActionMsgTypeUnreadInfo.base,}};

static void InitDefaultsSYSMsgUnreadCntRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_SYSMsgUnreadCntRequest_default_instance_;
    new (ptr) ::wbapi::SYSMsgUnreadCntRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::SYSMsgUnreadCntRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SYSMsgUnreadCntRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSYSMsgUnreadCntRequest}, {}};

static void InitDefaultsSYSMsgUnreadCntResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_SYSMsgUnreadCntResponse_default_instance_;
    new (ptr) ::wbapi::SYSMsgUnreadCntResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::SYSMsgUnreadCntResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_SYSMsgUnreadCntResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsSYSMsgUnreadCntResponse}, {
      &protobuf_msg_5funread_2eproto::scc_info_FamilyActionMsgUnreadInfo.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_FamilyActionMsgTypeUnreadInfo.base);
  ::google::protobuf::internal::InitSCC(&scc_info_FamilyActionMsgUnreadInfo.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SYSMsgUnreadCntRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SYSMsgUnreadCntResponse.base);
}

}  // namespace protobuf_msg_5funread_2eproto
namespace wbapi {
bool SYSMsgUnreadType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void FamilyActionMsgTypeUnreadInfo::InitAsDefaultInstance() {
  ::wbapi::_FamilyActionMsgTypeUnreadInfo_default_instance_._instance.get_mutable()->latest_msg_ = const_cast< ::wbapi::FamilyActionMsg*>(
      ::wbapi::FamilyActionMsg::internal_default_instance());
}
void FamilyActionMsgTypeUnreadInfo::clear_latest_msg() {
  if (GetArenaNoVirtual() == NULL && latest_msg_ != NULL) {
    delete latest_msg_;
  }
  latest_msg_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FamilyActionMsgTypeUnreadInfo::kMsgTypeFieldNumber;
const int FamilyActionMsgTypeUnreadInfo::kUnreadCntFieldNumber;
const int FamilyActionMsgTypeUnreadInfo::kLatestMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FamilyActionMsgTypeUnreadInfo::FamilyActionMsgTypeUnreadInfo()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_msg_5funread_2eproto::scc_info_FamilyActionMsgTypeUnreadInfo.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.FamilyActionMsgTypeUnreadInfo)
}
FamilyActionMsgTypeUnreadInfo::FamilyActionMsgTypeUnreadInfo(const FamilyActionMsgTypeUnreadInfo& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_latest_msg()) {
    latest_msg_ = new ::wbapi::FamilyActionMsg(*from.latest_msg_);
  } else {
    latest_msg_ = NULL;
  }
  ::memcpy(&msg_type_, &from.msg_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&unread_cnt_) -
    reinterpret_cast<char*>(&msg_type_)) + sizeof(unread_cnt_));
  // @@protoc_insertion_point(copy_constructor:wbapi.FamilyActionMsgTypeUnreadInfo)
}

void FamilyActionMsgTypeUnreadInfo::SharedCtor() {
  ::memset(&latest_msg_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&unread_cnt_) -
      reinterpret_cast<char*>(&latest_msg_)) + sizeof(unread_cnt_));
}

FamilyActionMsgTypeUnreadInfo::~FamilyActionMsgTypeUnreadInfo() {
  // @@protoc_insertion_point(destructor:wbapi.FamilyActionMsgTypeUnreadInfo)
  SharedDtor();
}

void FamilyActionMsgTypeUnreadInfo::SharedDtor() {
  if (this != internal_default_instance()) delete latest_msg_;
}

void FamilyActionMsgTypeUnreadInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FamilyActionMsgTypeUnreadInfo& FamilyActionMsgTypeUnreadInfo::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_msg_5funread_2eproto::scc_info_FamilyActionMsgTypeUnreadInfo.base);
  return *internal_default_instance();
}


void FamilyActionMsgTypeUnreadInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.FamilyActionMsgTypeUnreadInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && latest_msg_ != NULL) {
    delete latest_msg_;
  }
  latest_msg_ = NULL;
  ::memset(&msg_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&unread_cnt_) -
      reinterpret_cast<char*>(&msg_type_)) + sizeof(unread_cnt_));
  _internal_metadata_.Clear();
}

bool FamilyActionMsgTypeUnreadInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.FamilyActionMsgTypeUnreadInfo)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .wbapi.FamilyActionMsgType msg_type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_msg_type(static_cast< ::wbapi::FamilyActionMsgType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 unread_cnt = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &unread_cnt_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .wbapi.FamilyActionMsg latest_msg = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_latest_msg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.FamilyActionMsgTypeUnreadInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.FamilyActionMsgTypeUnreadInfo)
  return false;
#undef DO_
}

void FamilyActionMsgTypeUnreadInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.FamilyActionMsgTypeUnreadInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .wbapi.FamilyActionMsgType msg_type = 1;
  if (this->msg_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->msg_type(), output);
  }

  // int32 unread_cnt = 2;
  if (this->unread_cnt() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->unread_cnt(), output);
  }

  // .wbapi.FamilyActionMsg latest_msg = 3;
  if (this->has_latest_msg()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, this->_internal_latest_msg(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.FamilyActionMsgTypeUnreadInfo)
}

size_t FamilyActionMsgTypeUnreadInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.FamilyActionMsgTypeUnreadInfo)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // .wbapi.FamilyActionMsg latest_msg = 3;
  if (this->has_latest_msg()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *latest_msg_);
  }

  // .wbapi.FamilyActionMsgType msg_type = 1;
  if (this->msg_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->msg_type());
  }

  // int32 unread_cnt = 2;
  if (this->unread_cnt() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->unread_cnt());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FamilyActionMsgTypeUnreadInfo::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const FamilyActionMsgTypeUnreadInfo*>(&from));
}

void FamilyActionMsgTypeUnreadInfo::MergeFrom(const FamilyActionMsgTypeUnreadInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.FamilyActionMsgTypeUnreadInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_latest_msg()) {
    mutable_latest_msg()->::wbapi::FamilyActionMsg::MergeFrom(from.latest_msg());
  }
  if (from.msg_type() != 0) {
    set_msg_type(from.msg_type());
  }
  if (from.unread_cnt() != 0) {
    set_unread_cnt(from.unread_cnt());
  }
}

void FamilyActionMsgTypeUnreadInfo::CopyFrom(const FamilyActionMsgTypeUnreadInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.FamilyActionMsgTypeUnreadInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FamilyActionMsgTypeUnreadInfo::IsInitialized() const {
  return true;
}

void FamilyActionMsgTypeUnreadInfo::Swap(FamilyActionMsgTypeUnreadInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FamilyActionMsgTypeUnreadInfo::InternalSwap(FamilyActionMsgTypeUnreadInfo* other) {
  using std::swap;
  swap(latest_msg_, other->latest_msg_);
  swap(msg_type_, other->msg_type_);
  swap(unread_cnt_, other->unread_cnt_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string FamilyActionMsgTypeUnreadInfo::GetTypeName() const {
  return "wbapi.FamilyActionMsgTypeUnreadInfo";
}


// ===================================================================

void FamilyActionMsgUnreadInfo::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FamilyActionMsgUnreadInfo::kTotalCntFieldNumber;
const int FamilyActionMsgUnreadInfo::kUnreadInfosFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FamilyActionMsgUnreadInfo::FamilyActionMsgUnreadInfo()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_msg_5funread_2eproto::scc_info_FamilyActionMsgUnreadInfo.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.FamilyActionMsgUnreadInfo)
}
FamilyActionMsgUnreadInfo::FamilyActionMsgUnreadInfo(const FamilyActionMsgUnreadInfo& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      unread_infos_(from.unread_infos_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  total_cnt_ = from.total_cnt_;
  // @@protoc_insertion_point(copy_constructor:wbapi.FamilyActionMsgUnreadInfo)
}

void FamilyActionMsgUnreadInfo::SharedCtor() {
  total_cnt_ = 0;
}

FamilyActionMsgUnreadInfo::~FamilyActionMsgUnreadInfo() {
  // @@protoc_insertion_point(destructor:wbapi.FamilyActionMsgUnreadInfo)
  SharedDtor();
}

void FamilyActionMsgUnreadInfo::SharedDtor() {
}

void FamilyActionMsgUnreadInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FamilyActionMsgUnreadInfo& FamilyActionMsgUnreadInfo::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_msg_5funread_2eproto::scc_info_FamilyActionMsgUnreadInfo.base);
  return *internal_default_instance();
}


void FamilyActionMsgUnreadInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.FamilyActionMsgUnreadInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  unread_infos_.Clear();
  total_cnt_ = 0;
  _internal_metadata_.Clear();
}

bool FamilyActionMsgUnreadInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.FamilyActionMsgUnreadInfo)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 total_cnt = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &total_cnt_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .wbapi.FamilyActionMsgTypeUnreadInfo unread_infos = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_unread_infos()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.FamilyActionMsgUnreadInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.FamilyActionMsgUnreadInfo)
  return false;
#undef DO_
}

void FamilyActionMsgUnreadInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.FamilyActionMsgUnreadInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 total_cnt = 1;
  if (this->total_cnt() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->total_cnt(), output);
  }

  // repeated .wbapi.FamilyActionMsgTypeUnreadInfo unread_infos = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->unread_infos_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2,
      this->unread_infos(static_cast<int>(i)),
      output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.FamilyActionMsgUnreadInfo)
}

size_t FamilyActionMsgUnreadInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.FamilyActionMsgUnreadInfo)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // repeated .wbapi.FamilyActionMsgTypeUnreadInfo unread_infos = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->unread_infos_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->unread_infos(static_cast<int>(i)));
    }
  }

  // int32 total_cnt = 1;
  if (this->total_cnt() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->total_cnt());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FamilyActionMsgUnreadInfo::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const FamilyActionMsgUnreadInfo*>(&from));
}

void FamilyActionMsgUnreadInfo::MergeFrom(const FamilyActionMsgUnreadInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.FamilyActionMsgUnreadInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  unread_infos_.MergeFrom(from.unread_infos_);
  if (from.total_cnt() != 0) {
    set_total_cnt(from.total_cnt());
  }
}

void FamilyActionMsgUnreadInfo::CopyFrom(const FamilyActionMsgUnreadInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.FamilyActionMsgUnreadInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FamilyActionMsgUnreadInfo::IsInitialized() const {
  return true;
}

void FamilyActionMsgUnreadInfo::Swap(FamilyActionMsgUnreadInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FamilyActionMsgUnreadInfo::InternalSwap(FamilyActionMsgUnreadInfo* other) {
  using std::swap;
  CastToBase(&unread_infos_)->InternalSwap(CastToBase(&other->unread_infos_));
  swap(total_cnt_, other->total_cnt_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string FamilyActionMsgUnreadInfo::GetTypeName() const {
  return "wbapi.FamilyActionMsgUnreadInfo";
}


// ===================================================================

void SYSMsgUnreadCntRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SYSMsgUnreadCntRequest::kUnreadTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SYSMsgUnreadCntRequest::SYSMsgUnreadCntRequest()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_msg_5funread_2eproto::scc_info_SYSMsgUnreadCntRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.SYSMsgUnreadCntRequest)
}
SYSMsgUnreadCntRequest::SYSMsgUnreadCntRequest(const SYSMsgUnreadCntRequest& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  unread_type_ = from.unread_type_;
  // @@protoc_insertion_point(copy_constructor:wbapi.SYSMsgUnreadCntRequest)
}

void SYSMsgUnreadCntRequest::SharedCtor() {
  unread_type_ = 0;
}

SYSMsgUnreadCntRequest::~SYSMsgUnreadCntRequest() {
  // @@protoc_insertion_point(destructor:wbapi.SYSMsgUnreadCntRequest)
  SharedDtor();
}

void SYSMsgUnreadCntRequest::SharedDtor() {
}

void SYSMsgUnreadCntRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SYSMsgUnreadCntRequest& SYSMsgUnreadCntRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_msg_5funread_2eproto::scc_info_SYSMsgUnreadCntRequest.base);
  return *internal_default_instance();
}


void SYSMsgUnreadCntRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.SYSMsgUnreadCntRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  unread_type_ = 0;
  _internal_metadata_.Clear();
}

bool SYSMsgUnreadCntRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.SYSMsgUnreadCntRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .wbapi.SYSMsgUnreadType unread_type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_unread_type(static_cast< ::wbapi::SYSMsgUnreadType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.SYSMsgUnreadCntRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.SYSMsgUnreadCntRequest)
  return false;
#undef DO_
}

void SYSMsgUnreadCntRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.SYSMsgUnreadCntRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .wbapi.SYSMsgUnreadType unread_type = 1;
  if (this->unread_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->unread_type(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.SYSMsgUnreadCntRequest)
}

size_t SYSMsgUnreadCntRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.SYSMsgUnreadCntRequest)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // .wbapi.SYSMsgUnreadType unread_type = 1;
  if (this->unread_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->unread_type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SYSMsgUnreadCntRequest::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const SYSMsgUnreadCntRequest*>(&from));
}

void SYSMsgUnreadCntRequest::MergeFrom(const SYSMsgUnreadCntRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.SYSMsgUnreadCntRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.unread_type() != 0) {
    set_unread_type(from.unread_type());
  }
}

void SYSMsgUnreadCntRequest::CopyFrom(const SYSMsgUnreadCntRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.SYSMsgUnreadCntRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SYSMsgUnreadCntRequest::IsInitialized() const {
  return true;
}

void SYSMsgUnreadCntRequest::Swap(SYSMsgUnreadCntRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SYSMsgUnreadCntRequest::InternalSwap(SYSMsgUnreadCntRequest* other) {
  using std::swap;
  swap(unread_type_, other->unread_type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string SYSMsgUnreadCntRequest::GetTypeName() const {
  return "wbapi.SYSMsgUnreadCntRequest";
}


// ===================================================================

void SYSMsgUnreadCntResponse::InitAsDefaultInstance() {
  ::wbapi::_SYSMsgUnreadCntResponse_default_instance_._instance.get_mutable()->family_action_msg_unread_info_ = const_cast< ::wbapi::FamilyActionMsgUnreadInfo*>(
      ::wbapi::FamilyActionMsgUnreadInfo::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SYSMsgUnreadCntResponse::kErrorCodeFieldNumber;
const int SYSMsgUnreadCntResponse::kUnreadTypeFieldNumber;
const int SYSMsgUnreadCntResponse::kFamilyActionMsgUnreadInfoFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SYSMsgUnreadCntResponse::SYSMsgUnreadCntResponse()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_msg_5funread_2eproto::scc_info_SYSMsgUnreadCntResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.SYSMsgUnreadCntResponse)
}
SYSMsgUnreadCntResponse::SYSMsgUnreadCntResponse(const SYSMsgUnreadCntResponse& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_family_action_msg_unread_info()) {
    family_action_msg_unread_info_ = new ::wbapi::FamilyActionMsgUnreadInfo(*from.family_action_msg_unread_info_);
  } else {
    family_action_msg_unread_info_ = NULL;
  }
  ::memcpy(&error_code_, &from.error_code_,
    static_cast<size_t>(reinterpret_cast<char*>(&unread_type_) -
    reinterpret_cast<char*>(&error_code_)) + sizeof(unread_type_));
  // @@protoc_insertion_point(copy_constructor:wbapi.SYSMsgUnreadCntResponse)
}

void SYSMsgUnreadCntResponse::SharedCtor() {
  ::memset(&family_action_msg_unread_info_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&unread_type_) -
      reinterpret_cast<char*>(&family_action_msg_unread_info_)) + sizeof(unread_type_));
}

SYSMsgUnreadCntResponse::~SYSMsgUnreadCntResponse() {
  // @@protoc_insertion_point(destructor:wbapi.SYSMsgUnreadCntResponse)
  SharedDtor();
}

void SYSMsgUnreadCntResponse::SharedDtor() {
  if (this != internal_default_instance()) delete family_action_msg_unread_info_;
}

void SYSMsgUnreadCntResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SYSMsgUnreadCntResponse& SYSMsgUnreadCntResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_msg_5funread_2eproto::scc_info_SYSMsgUnreadCntResponse.base);
  return *internal_default_instance();
}


void SYSMsgUnreadCntResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.SYSMsgUnreadCntResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && family_action_msg_unread_info_ != NULL) {
    delete family_action_msg_unread_info_;
  }
  family_action_msg_unread_info_ = NULL;
  ::memset(&error_code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&unread_type_) -
      reinterpret_cast<char*>(&error_code_)) + sizeof(unread_type_));
  _internal_metadata_.Clear();
}

bool SYSMsgUnreadCntResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.SYSMsgUnreadCntResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 error_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .wbapi.SYSMsgUnreadType unread_type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_unread_type(static_cast< ::wbapi::SYSMsgUnreadType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .wbapi.FamilyActionMsgUnreadInfo family_action_msg_unread_info = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_family_action_msg_unread_info()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.SYSMsgUnreadCntResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.SYSMsgUnreadCntResponse)
  return false;
#undef DO_
}

void SYSMsgUnreadCntResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.SYSMsgUnreadCntResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error_code(), output);
  }

  // .wbapi.SYSMsgUnreadType unread_type = 2;
  if (this->unread_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->unread_type(), output);
  }

  // .wbapi.FamilyActionMsgUnreadInfo family_action_msg_unread_info = 3;
  if (this->has_family_action_msg_unread_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, this->_internal_family_action_msg_unread_info(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.SYSMsgUnreadCntResponse)
}

size_t SYSMsgUnreadCntResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.SYSMsgUnreadCntResponse)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // .wbapi.FamilyActionMsgUnreadInfo family_action_msg_unread_info = 3;
  if (this->has_family_action_msg_unread_info()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *family_action_msg_unread_info_);
  }

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error_code());
  }

  // .wbapi.SYSMsgUnreadType unread_type = 2;
  if (this->unread_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->unread_type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SYSMsgUnreadCntResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const SYSMsgUnreadCntResponse*>(&from));
}

void SYSMsgUnreadCntResponse::MergeFrom(const SYSMsgUnreadCntResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.SYSMsgUnreadCntResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_family_action_msg_unread_info()) {
    mutable_family_action_msg_unread_info()->::wbapi::FamilyActionMsgUnreadInfo::MergeFrom(from.family_action_msg_unread_info());
  }
  if (from.error_code() != 0) {
    set_error_code(from.error_code());
  }
  if (from.unread_type() != 0) {
    set_unread_type(from.unread_type());
  }
}

void SYSMsgUnreadCntResponse::CopyFrom(const SYSMsgUnreadCntResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.SYSMsgUnreadCntResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SYSMsgUnreadCntResponse::IsInitialized() const {
  return true;
}

void SYSMsgUnreadCntResponse::Swap(SYSMsgUnreadCntResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SYSMsgUnreadCntResponse::InternalSwap(SYSMsgUnreadCntResponse* other) {
  using std::swap;
  swap(family_action_msg_unread_info_, other->family_action_msg_unread_info_);
  swap(error_code_, other->error_code_);
  swap(unread_type_, other->unread_type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string SYSMsgUnreadCntResponse::GetTypeName() const {
  return "wbapi.SYSMsgUnreadCntResponse";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace wbapi
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::FamilyActionMsgTypeUnreadInfo* Arena::CreateMaybeMessage< ::wbapi::FamilyActionMsgTypeUnreadInfo >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::FamilyActionMsgTypeUnreadInfo >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::FamilyActionMsgUnreadInfo* Arena::CreateMaybeMessage< ::wbapi::FamilyActionMsgUnreadInfo >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::FamilyActionMsgUnreadInfo >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::SYSMsgUnreadCntRequest* Arena::CreateMaybeMessage< ::wbapi::SYSMsgUnreadCntRequest >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::SYSMsgUnreadCntRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::SYSMsgUnreadCntResponse* Arena::CreateMaybeMessage< ::wbapi::SYSMsgUnreadCntResponse >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::SYSMsgUnreadCntResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
