// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

#include "push.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_device_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_device_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_DeviceAlarmInfo;
}  // namespace protobuf_device_2eproto
namespace wbapi {
class BindPushTokenRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BindPushTokenRequest>
      _instance;
} _BindPushTokenRequest_default_instance_;
class BindPushTokenResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BindPushTokenResponse>
      _instance;
} _BindPushTokenResponse_default_instance_;
class PushSettingRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PushSettingRequest>
      _instance;
} _PushSettingRequest_default_instance_;
class PushSettingResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PushSettingResponse>
      _instance;
} _PushSettingResponse_default_instance_;
class GetPushSettingRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetPushSettingRequest>
      _instance;
} _GetPushSettingRequest_default_instance_;
class GetPushSettingResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetPushSettingResponse>
      _instance;
} _GetPushSettingResponse_default_instance_;
class DeviceAlarmOfflineMsgDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DeviceAlarmOfflineMsg>
      _instance;
} _DeviceAlarmOfflineMsg_default_instance_;
class PushPrivateMsgRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PushPrivateMsgRequest>
      _instance;
} _PushPrivateMsgRequest_default_instance_;
class PushPrivateMsgResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PushPrivateMsgResponse>
      _instance;
} _PushPrivateMsgResponse_default_instance_;
}  // namespace wbapi
namespace protobuf_push_2eproto {
static void InitDefaultsBindPushTokenRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_BindPushTokenRequest_default_instance_;
    new (ptr) ::wbapi::BindPushTokenRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::BindPushTokenRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_BindPushTokenRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBindPushTokenRequest}, {}};

static void InitDefaultsBindPushTokenResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_BindPushTokenResponse_default_instance_;
    new (ptr) ::wbapi::BindPushTokenResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::BindPushTokenResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_BindPushTokenResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBindPushTokenResponse}, {}};

static void InitDefaultsPushSettingRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_PushSettingRequest_default_instance_;
    new (ptr) ::wbapi::PushSettingRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::PushSettingRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PushSettingRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPushSettingRequest}, {}};

static void InitDefaultsPushSettingResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_PushSettingResponse_default_instance_;
    new (ptr) ::wbapi::PushSettingResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::PushSettingResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PushSettingResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPushSettingResponse}, {}};

static void InitDefaultsGetPushSettingRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_GetPushSettingRequest_default_instance_;
    new (ptr) ::wbapi::GetPushSettingRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::GetPushSettingRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GetPushSettingRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGetPushSettingRequest}, {}};

static void InitDefaultsGetPushSettingResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_GetPushSettingResponse_default_instance_;
    new (ptr) ::wbapi::GetPushSettingResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::GetPushSettingResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GetPushSettingResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGetPushSettingResponse}, {}};

static void InitDefaultsDeviceAlarmOfflineMsg() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_DeviceAlarmOfflineMsg_default_instance_;
    new (ptr) ::wbapi::DeviceAlarmOfflineMsg();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::DeviceAlarmOfflineMsg::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_DeviceAlarmOfflineMsg =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsDeviceAlarmOfflineMsg}, {
      &protobuf_device_2eproto::scc_info_DeviceAlarmInfo.base,}};

static void InitDefaultsPushPrivateMsgRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_PushPrivateMsgRequest_default_instance_;
    new (ptr) ::wbapi::PushPrivateMsgRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::PushPrivateMsgRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PushPrivateMsgRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPushPrivateMsgRequest}, {}};

static void InitDefaultsPushPrivateMsgResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_PushPrivateMsgResponse_default_instance_;
    new (ptr) ::wbapi::PushPrivateMsgResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::PushPrivateMsgResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PushPrivateMsgResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPushPrivateMsgResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_BindPushTokenRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_BindPushTokenResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PushSettingRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PushSettingResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GetPushSettingRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GetPushSettingResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DeviceAlarmOfflineMsg.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PushPrivateMsgRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PushPrivateMsgResponse.base);
}

}  // namespace protobuf_push_2eproto
namespace wbapi {

// ===================================================================

void BindPushTokenRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BindPushTokenRequest::kTokenFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BindPushTokenRequest::BindPushTokenRequest()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_push_2eproto::scc_info_BindPushTokenRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.BindPushTokenRequest)
}
BindPushTokenRequest::BindPushTokenRequest(const BindPushTokenRequest& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.token().size() > 0) {
    token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.token_);
  }
  // @@protoc_insertion_point(copy_constructor:wbapi.BindPushTokenRequest)
}

void BindPushTokenRequest::SharedCtor() {
  token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

BindPushTokenRequest::~BindPushTokenRequest() {
  // @@protoc_insertion_point(destructor:wbapi.BindPushTokenRequest)
  SharedDtor();
}

void BindPushTokenRequest::SharedDtor() {
  token_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void BindPushTokenRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const BindPushTokenRequest& BindPushTokenRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_push_2eproto::scc_info_BindPushTokenRequest.base);
  return *internal_default_instance();
}


void BindPushTokenRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.BindPushTokenRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool BindPushTokenRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.BindPushTokenRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string token = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_token()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->token().data(), static_cast<int>(this->token().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "wbapi.BindPushTokenRequest.token"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.BindPushTokenRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.BindPushTokenRequest)
  return false;
#undef DO_
}

void BindPushTokenRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.BindPushTokenRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string token = 1;
  if (this->token().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->token().data(), static_cast<int>(this->token().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "wbapi.BindPushTokenRequest.token");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->token(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.BindPushTokenRequest)
}

size_t BindPushTokenRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.BindPushTokenRequest)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string token = 1;
  if (this->token().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->token());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BindPushTokenRequest::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const BindPushTokenRequest*>(&from));
}

void BindPushTokenRequest::MergeFrom(const BindPushTokenRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.BindPushTokenRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.token().size() > 0) {

    token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.token_);
  }
}

void BindPushTokenRequest::CopyFrom(const BindPushTokenRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.BindPushTokenRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BindPushTokenRequest::IsInitialized() const {
  return true;
}

void BindPushTokenRequest::Swap(BindPushTokenRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BindPushTokenRequest::InternalSwap(BindPushTokenRequest* other) {
  using std::swap;
  token_.Swap(&other->token_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string BindPushTokenRequest::GetTypeName() const {
  return "wbapi.BindPushTokenRequest";
}


// ===================================================================

void BindPushTokenResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BindPushTokenResponse::kErrorCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BindPushTokenResponse::BindPushTokenResponse()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_push_2eproto::scc_info_BindPushTokenResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.BindPushTokenResponse)
}
BindPushTokenResponse::BindPushTokenResponse(const BindPushTokenResponse& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  error_code_ = from.error_code_;
  // @@protoc_insertion_point(copy_constructor:wbapi.BindPushTokenResponse)
}

void BindPushTokenResponse::SharedCtor() {
  error_code_ = 0;
}

BindPushTokenResponse::~BindPushTokenResponse() {
  // @@protoc_insertion_point(destructor:wbapi.BindPushTokenResponse)
  SharedDtor();
}

void BindPushTokenResponse::SharedDtor() {
}

void BindPushTokenResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const BindPushTokenResponse& BindPushTokenResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_push_2eproto::scc_info_BindPushTokenResponse.base);
  return *internal_default_instance();
}


void BindPushTokenResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.BindPushTokenResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  error_code_ = 0;
  _internal_metadata_.Clear();
}

bool BindPushTokenResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.BindPushTokenResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 error_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.BindPushTokenResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.BindPushTokenResponse)
  return false;
#undef DO_
}

void BindPushTokenResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.BindPushTokenResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error_code(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.BindPushTokenResponse)
}

size_t BindPushTokenResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.BindPushTokenResponse)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error_code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BindPushTokenResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const BindPushTokenResponse*>(&from));
}

void BindPushTokenResponse::MergeFrom(const BindPushTokenResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.BindPushTokenResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.error_code() != 0) {
    set_error_code(from.error_code());
  }
}

void BindPushTokenResponse::CopyFrom(const BindPushTokenResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.BindPushTokenResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BindPushTokenResponse::IsInitialized() const {
  return true;
}

void BindPushTokenResponse::Swap(BindPushTokenResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BindPushTokenResponse::InternalSwap(BindPushTokenResponse* other) {
  using std::swap;
  swap(error_code_, other->error_code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string BindPushTokenResponse::GetTypeName() const {
  return "wbapi.BindPushTokenResponse";
}


// ===================================================================

void PushSettingRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PushSettingRequest::kQuietFieldNumber;
const int PushSettingRequest::kSmsEnabledFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PushSettingRequest::PushSettingRequest()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_push_2eproto::scc_info_PushSettingRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.PushSettingRequest)
}
PushSettingRequest::PushSettingRequest(const PushSettingRequest& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&quiet_, &from.quiet_,
    static_cast<size_t>(reinterpret_cast<char*>(&sms_enabled_) -
    reinterpret_cast<char*>(&quiet_)) + sizeof(sms_enabled_));
  // @@protoc_insertion_point(copy_constructor:wbapi.PushSettingRequest)
}

void PushSettingRequest::SharedCtor() {
  ::memset(&quiet_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sms_enabled_) -
      reinterpret_cast<char*>(&quiet_)) + sizeof(sms_enabled_));
}

PushSettingRequest::~PushSettingRequest() {
  // @@protoc_insertion_point(destructor:wbapi.PushSettingRequest)
  SharedDtor();
}

void PushSettingRequest::SharedDtor() {
}

void PushSettingRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PushSettingRequest& PushSettingRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_push_2eproto::scc_info_PushSettingRequest.base);
  return *internal_default_instance();
}


void PushSettingRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.PushSettingRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&quiet_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sms_enabled_) -
      reinterpret_cast<char*>(&quiet_)) + sizeof(sms_enabled_));
  _internal_metadata_.Clear();
}

bool PushSettingRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.PushSettingRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 quiet = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &quiet_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 sms_enabled = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sms_enabled_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.PushSettingRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.PushSettingRequest)
  return false;
#undef DO_
}

void PushSettingRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.PushSettingRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 quiet = 1;
  if (this->quiet() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->quiet(), output);
  }

  // int32 sms_enabled = 2;
  if (this->sms_enabled() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->sms_enabled(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.PushSettingRequest)
}

size_t PushSettingRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.PushSettingRequest)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // int32 quiet = 1;
  if (this->quiet() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->quiet());
  }

  // int32 sms_enabled = 2;
  if (this->sms_enabled() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->sms_enabled());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PushSettingRequest::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const PushSettingRequest*>(&from));
}

void PushSettingRequest::MergeFrom(const PushSettingRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.PushSettingRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.quiet() != 0) {
    set_quiet(from.quiet());
  }
  if (from.sms_enabled() != 0) {
    set_sms_enabled(from.sms_enabled());
  }
}

void PushSettingRequest::CopyFrom(const PushSettingRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.PushSettingRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PushSettingRequest::IsInitialized() const {
  return true;
}

void PushSettingRequest::Swap(PushSettingRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PushSettingRequest::InternalSwap(PushSettingRequest* other) {
  using std::swap;
  swap(quiet_, other->quiet_);
  swap(sms_enabled_, other->sms_enabled_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string PushSettingRequest::GetTypeName() const {
  return "wbapi.PushSettingRequest";
}


// ===================================================================

void PushSettingResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PushSettingResponse::kErrorCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PushSettingResponse::PushSettingResponse()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_push_2eproto::scc_info_PushSettingResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.PushSettingResponse)
}
PushSettingResponse::PushSettingResponse(const PushSettingResponse& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  error_code_ = from.error_code_;
  // @@protoc_insertion_point(copy_constructor:wbapi.PushSettingResponse)
}

void PushSettingResponse::SharedCtor() {
  error_code_ = 0;
}

PushSettingResponse::~PushSettingResponse() {
  // @@protoc_insertion_point(destructor:wbapi.PushSettingResponse)
  SharedDtor();
}

void PushSettingResponse::SharedDtor() {
}

void PushSettingResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PushSettingResponse& PushSettingResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_push_2eproto::scc_info_PushSettingResponse.base);
  return *internal_default_instance();
}


void PushSettingResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.PushSettingResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  error_code_ = 0;
  _internal_metadata_.Clear();
}

bool PushSettingResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.PushSettingResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 error_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.PushSettingResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.PushSettingResponse)
  return false;
#undef DO_
}

void PushSettingResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.PushSettingResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error_code(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.PushSettingResponse)
}

size_t PushSettingResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.PushSettingResponse)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error_code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PushSettingResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const PushSettingResponse*>(&from));
}

void PushSettingResponse::MergeFrom(const PushSettingResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.PushSettingResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.error_code() != 0) {
    set_error_code(from.error_code());
  }
}

void PushSettingResponse::CopyFrom(const PushSettingResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.PushSettingResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PushSettingResponse::IsInitialized() const {
  return true;
}

void PushSettingResponse::Swap(PushSettingResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PushSettingResponse::InternalSwap(PushSettingResponse* other) {
  using std::swap;
  swap(error_code_, other->error_code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string PushSettingResponse::GetTypeName() const {
  return "wbapi.PushSettingResponse";
}


// ===================================================================

void GetPushSettingRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetPushSettingRequest::GetPushSettingRequest()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_push_2eproto::scc_info_GetPushSettingRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.GetPushSettingRequest)
}
GetPushSettingRequest::GetPushSettingRequest(const GetPushSettingRequest& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:wbapi.GetPushSettingRequest)
}

void GetPushSettingRequest::SharedCtor() {
}

GetPushSettingRequest::~GetPushSettingRequest() {
  // @@protoc_insertion_point(destructor:wbapi.GetPushSettingRequest)
  SharedDtor();
}

void GetPushSettingRequest::SharedDtor() {
}

void GetPushSettingRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetPushSettingRequest& GetPushSettingRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_push_2eproto::scc_info_GetPushSettingRequest.base);
  return *internal_default_instance();
}


void GetPushSettingRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.GetPushSettingRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool GetPushSettingRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.GetPushSettingRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(
        input, tag, &unknown_fields_stream));
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.GetPushSettingRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.GetPushSettingRequest)
  return false;
#undef DO_
}

void GetPushSettingRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.GetPushSettingRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.GetPushSettingRequest)
}

size_t GetPushSettingRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.GetPushSettingRequest)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetPushSettingRequest::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const GetPushSettingRequest*>(&from));
}

void GetPushSettingRequest::MergeFrom(const GetPushSettingRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.GetPushSettingRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void GetPushSettingRequest::CopyFrom(const GetPushSettingRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.GetPushSettingRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetPushSettingRequest::IsInitialized() const {
  return true;
}

void GetPushSettingRequest::Swap(GetPushSettingRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetPushSettingRequest::InternalSwap(GetPushSettingRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string GetPushSettingRequest::GetTypeName() const {
  return "wbapi.GetPushSettingRequest";
}


// ===================================================================

void GetPushSettingResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetPushSettingResponse::kErrorCodeFieldNumber;
const int GetPushSettingResponse::kQuietFieldNumber;
const int GetPushSettingResponse::kSmsEnabledFieldNumber;
const int GetPushSettingResponse::kTokenFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetPushSettingResponse::GetPushSettingResponse()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_push_2eproto::scc_info_GetPushSettingResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.GetPushSettingResponse)
}
GetPushSettingResponse::GetPushSettingResponse(const GetPushSettingResponse& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.token().size() > 0) {
    token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.token_);
  }
  ::memcpy(&error_code_, &from.error_code_,
    static_cast<size_t>(reinterpret_cast<char*>(&sms_enabled_) -
    reinterpret_cast<char*>(&error_code_)) + sizeof(sms_enabled_));
  // @@protoc_insertion_point(copy_constructor:wbapi.GetPushSettingResponse)
}

void GetPushSettingResponse::SharedCtor() {
  token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&error_code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sms_enabled_) -
      reinterpret_cast<char*>(&error_code_)) + sizeof(sms_enabled_));
}

GetPushSettingResponse::~GetPushSettingResponse() {
  // @@protoc_insertion_point(destructor:wbapi.GetPushSettingResponse)
  SharedDtor();
}

void GetPushSettingResponse::SharedDtor() {
  token_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GetPushSettingResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetPushSettingResponse& GetPushSettingResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_push_2eproto::scc_info_GetPushSettingResponse.base);
  return *internal_default_instance();
}


void GetPushSettingResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.GetPushSettingResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&error_code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sms_enabled_) -
      reinterpret_cast<char*>(&error_code_)) + sizeof(sms_enabled_));
  _internal_metadata_.Clear();
}

bool GetPushSettingResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.GetPushSettingResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 error_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 quiet = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &quiet_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 sms_enabled = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sms_enabled_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string token = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_token()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->token().data(), static_cast<int>(this->token().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "wbapi.GetPushSettingResponse.token"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.GetPushSettingResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.GetPushSettingResponse)
  return false;
#undef DO_
}

void GetPushSettingResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.GetPushSettingResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error_code(), output);
  }

  // int32 quiet = 2;
  if (this->quiet() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->quiet(), output);
  }

  // int32 sms_enabled = 3;
  if (this->sms_enabled() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->sms_enabled(), output);
  }

  // string token = 4;
  if (this->token().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->token().data(), static_cast<int>(this->token().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "wbapi.GetPushSettingResponse.token");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->token(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.GetPushSettingResponse)
}

size_t GetPushSettingResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.GetPushSettingResponse)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string token = 4;
  if (this->token().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->token());
  }

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error_code());
  }

  // int32 quiet = 2;
  if (this->quiet() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->quiet());
  }

  // int32 sms_enabled = 3;
  if (this->sms_enabled() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->sms_enabled());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetPushSettingResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const GetPushSettingResponse*>(&from));
}

void GetPushSettingResponse::MergeFrom(const GetPushSettingResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.GetPushSettingResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.token().size() > 0) {

    token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.token_);
  }
  if (from.error_code() != 0) {
    set_error_code(from.error_code());
  }
  if (from.quiet() != 0) {
    set_quiet(from.quiet());
  }
  if (from.sms_enabled() != 0) {
    set_sms_enabled(from.sms_enabled());
  }
}

void GetPushSettingResponse::CopyFrom(const GetPushSettingResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.GetPushSettingResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetPushSettingResponse::IsInitialized() const {
  return true;
}

void GetPushSettingResponse::Swap(GetPushSettingResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetPushSettingResponse::InternalSwap(GetPushSettingResponse* other) {
  using std::swap;
  token_.Swap(&other->token_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(error_code_, other->error_code_);
  swap(quiet_, other->quiet_);
  swap(sms_enabled_, other->sms_enabled_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string GetPushSettingResponse::GetTypeName() const {
  return "wbapi.GetPushSettingResponse";
}


// ===================================================================

void DeviceAlarmOfflineMsg::InitAsDefaultInstance() {
  ::wbapi::_DeviceAlarmOfflineMsg_default_instance_._instance.get_mutable()->extra_ = const_cast< ::wbapi::DeviceAlarmInfo*>(
      ::wbapi::DeviceAlarmInfo::internal_default_instance());
}
void DeviceAlarmOfflineMsg::clear_extra() {
  if (GetArenaNoVirtual() == NULL && extra_ != NULL) {
    delete extra_;
  }
  extra_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DeviceAlarmOfflineMsg::kUsersFieldNumber;
const int DeviceAlarmOfflineMsg::kAlertFieldNumber;
const int DeviceAlarmOfflineMsg::kExtraFieldNumber;
const int DeviceAlarmOfflineMsg::kRoomNameFieldNumber;
const int DeviceAlarmOfflineMsg::kDeviceNameFieldNumber;
const int DeviceAlarmOfflineMsg::kTimeFieldNumber;
const int DeviceAlarmOfflineMsg::kEventFieldNumber;
const int DeviceAlarmOfflineMsg::kActionFieldNumber;
const int DeviceAlarmOfflineMsg::kFamilyNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DeviceAlarmOfflineMsg::DeviceAlarmOfflineMsg()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_push_2eproto::scc_info_DeviceAlarmOfflineMsg.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.DeviceAlarmOfflineMsg)
}
DeviceAlarmOfflineMsg::DeviceAlarmOfflineMsg(const DeviceAlarmOfflineMsg& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      users_(from.users_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  alert_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.alert().size() > 0) {
    alert_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.alert_);
  }
  room_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.room_name().size() > 0) {
    room_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.room_name_);
  }
  device_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.device_name().size() > 0) {
    device_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.device_name_);
  }
  time_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.time().size() > 0) {
    time_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.time_);
  }
  event_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.event().size() > 0) {
    event_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.event_);
  }
  action_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.action().size() > 0) {
    action_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.action_);
  }
  family_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.family_name().size() > 0) {
    family_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.family_name_);
  }
  if (from.has_extra()) {
    extra_ = new ::wbapi::DeviceAlarmInfo(*from.extra_);
  } else {
    extra_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:wbapi.DeviceAlarmOfflineMsg)
}

void DeviceAlarmOfflineMsg::SharedCtor() {
  alert_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  room_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  device_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  event_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  action_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  family_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  extra_ = NULL;
}

DeviceAlarmOfflineMsg::~DeviceAlarmOfflineMsg() {
  // @@protoc_insertion_point(destructor:wbapi.DeviceAlarmOfflineMsg)
  SharedDtor();
}

void DeviceAlarmOfflineMsg::SharedDtor() {
  alert_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  room_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  device_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  event_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  action_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  family_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete extra_;
}

void DeviceAlarmOfflineMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DeviceAlarmOfflineMsg& DeviceAlarmOfflineMsg::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_push_2eproto::scc_info_DeviceAlarmOfflineMsg.base);
  return *internal_default_instance();
}


void DeviceAlarmOfflineMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.DeviceAlarmOfflineMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  users_.Clear();
  alert_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  room_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  device_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  event_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  action_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  family_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && extra_ != NULL) {
    delete extra_;
  }
  extra_ = NULL;
  _internal_metadata_.Clear();
}

bool DeviceAlarmOfflineMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.DeviceAlarmOfflineMsg)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int64 users = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, this->mutable_users())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 1, 10u, input, this->mutable_users())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string alert = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_alert()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->alert().data(), static_cast<int>(this->alert().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "wbapi.DeviceAlarmOfflineMsg.alert"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .wbapi.DeviceAlarmInfo extra = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_extra()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string room_name = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_room_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->room_name().data(), static_cast<int>(this->room_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "wbapi.DeviceAlarmOfflineMsg.room_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string device_name = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_device_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->device_name().data(), static_cast<int>(this->device_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "wbapi.DeviceAlarmOfflineMsg.device_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string time = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_time()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->time().data(), static_cast<int>(this->time().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "wbapi.DeviceAlarmOfflineMsg.time"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string event = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_event()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->event().data(), static_cast<int>(this->event().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "wbapi.DeviceAlarmOfflineMsg.event"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string action = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_action()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->action().data(), static_cast<int>(this->action().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "wbapi.DeviceAlarmOfflineMsg.action"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string family_name = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_family_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->family_name().data(), static_cast<int>(this->family_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "wbapi.DeviceAlarmOfflineMsg.family_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.DeviceAlarmOfflineMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.DeviceAlarmOfflineMsg)
  return false;
#undef DO_
}

void DeviceAlarmOfflineMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.DeviceAlarmOfflineMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int64 users = 1;
  if (this->users_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _users_cached_byte_size_));
  }
  for (int i = 0, n = this->users_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64NoTag(
      this->users(i), output);
  }

  // string alert = 2;
  if (this->alert().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->alert().data(), static_cast<int>(this->alert().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "wbapi.DeviceAlarmOfflineMsg.alert");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->alert(), output);
  }

  // .wbapi.DeviceAlarmInfo extra = 3;
  if (this->has_extra()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, this->_internal_extra(), output);
  }

  // string room_name = 5;
  if (this->room_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->room_name().data(), static_cast<int>(this->room_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "wbapi.DeviceAlarmOfflineMsg.room_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->room_name(), output);
  }

  // string device_name = 6;
  if (this->device_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->device_name().data(), static_cast<int>(this->device_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "wbapi.DeviceAlarmOfflineMsg.device_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->device_name(), output);
  }

  // string time = 7;
  if (this->time().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->time().data(), static_cast<int>(this->time().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "wbapi.DeviceAlarmOfflineMsg.time");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->time(), output);
  }

  // string event = 8;
  if (this->event().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->event().data(), static_cast<int>(this->event().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "wbapi.DeviceAlarmOfflineMsg.event");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->event(), output);
  }

  // string action = 9;
  if (this->action().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->action().data(), static_cast<int>(this->action().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "wbapi.DeviceAlarmOfflineMsg.action");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->action(), output);
  }

  // string family_name = 10;
  if (this->family_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->family_name().data(), static_cast<int>(this->family_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "wbapi.DeviceAlarmOfflineMsg.family_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->family_name(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.DeviceAlarmOfflineMsg)
}

size_t DeviceAlarmOfflineMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.DeviceAlarmOfflineMsg)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // repeated int64 users = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int64Size(this->users_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _users_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // string alert = 2;
  if (this->alert().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->alert());
  }

  // string room_name = 5;
  if (this->room_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->room_name());
  }

  // string device_name = 6;
  if (this->device_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->device_name());
  }

  // string time = 7;
  if (this->time().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->time());
  }

  // string event = 8;
  if (this->event().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->event());
  }

  // string action = 9;
  if (this->action().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->action());
  }

  // string family_name = 10;
  if (this->family_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->family_name());
  }

  // .wbapi.DeviceAlarmInfo extra = 3;
  if (this->has_extra()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *extra_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DeviceAlarmOfflineMsg::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const DeviceAlarmOfflineMsg*>(&from));
}

void DeviceAlarmOfflineMsg::MergeFrom(const DeviceAlarmOfflineMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.DeviceAlarmOfflineMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  users_.MergeFrom(from.users_);
  if (from.alert().size() > 0) {

    alert_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.alert_);
  }
  if (from.room_name().size() > 0) {

    room_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.room_name_);
  }
  if (from.device_name().size() > 0) {

    device_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.device_name_);
  }
  if (from.time().size() > 0) {

    time_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.time_);
  }
  if (from.event().size() > 0) {

    event_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.event_);
  }
  if (from.action().size() > 0) {

    action_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.action_);
  }
  if (from.family_name().size() > 0) {

    family_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.family_name_);
  }
  if (from.has_extra()) {
    mutable_extra()->::wbapi::DeviceAlarmInfo::MergeFrom(from.extra());
  }
}

void DeviceAlarmOfflineMsg::CopyFrom(const DeviceAlarmOfflineMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.DeviceAlarmOfflineMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeviceAlarmOfflineMsg::IsInitialized() const {
  return true;
}

void DeviceAlarmOfflineMsg::Swap(DeviceAlarmOfflineMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DeviceAlarmOfflineMsg::InternalSwap(DeviceAlarmOfflineMsg* other) {
  using std::swap;
  users_.InternalSwap(&other->users_);
  alert_.Swap(&other->alert_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  room_name_.Swap(&other->room_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  device_name_.Swap(&other->device_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  time_.Swap(&other->time_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  event_.Swap(&other->event_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  action_.Swap(&other->action_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  family_name_.Swap(&other->family_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(extra_, other->extra_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string DeviceAlarmOfflineMsg::GetTypeName() const {
  return "wbapi.DeviceAlarmOfflineMsg";
}


// ===================================================================

void PushPrivateMsgRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PushPrivateMsgRequest::kFlagFieldNumber;
const int PushPrivateMsgRequest::kMobileFieldNumber;
const int PushPrivateMsgRequest::kMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PushPrivateMsgRequest::PushPrivateMsgRequest()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_push_2eproto::scc_info_PushPrivateMsgRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.PushPrivateMsgRequest)
}
PushPrivateMsgRequest::PushPrivateMsgRequest(const PushPrivateMsgRequest& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  mobile_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.mobile().size() > 0) {
    mobile_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mobile_);
  }
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.msg().size() > 0) {
    msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_);
  }
  flag_ = from.flag_;
  // @@protoc_insertion_point(copy_constructor:wbapi.PushPrivateMsgRequest)
}

void PushPrivateMsgRequest::SharedCtor() {
  mobile_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  flag_ = 0;
}

PushPrivateMsgRequest::~PushPrivateMsgRequest() {
  // @@protoc_insertion_point(destructor:wbapi.PushPrivateMsgRequest)
  SharedDtor();
}

void PushPrivateMsgRequest::SharedDtor() {
  mobile_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PushPrivateMsgRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PushPrivateMsgRequest& PushPrivateMsgRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_push_2eproto::scc_info_PushPrivateMsgRequest.base);
  return *internal_default_instance();
}


void PushPrivateMsgRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.PushPrivateMsgRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  mobile_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  flag_ = 0;
  _internal_metadata_.Clear();
}

bool PushPrivateMsgRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.PushPrivateMsgRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 flag = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &flag_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string mobile = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_mobile()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->mobile().data(), static_cast<int>(this->mobile().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "wbapi.PushPrivateMsgRequest.mobile"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string msg = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->msg().data(), static_cast<int>(this->msg().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "wbapi.PushPrivateMsgRequest.msg"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.PushPrivateMsgRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.PushPrivateMsgRequest)
  return false;
#undef DO_
}

void PushPrivateMsgRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.PushPrivateMsgRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 flag = 1;
  if (this->flag() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->flag(), output);
  }

  // string mobile = 2;
  if (this->mobile().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->mobile().data(), static_cast<int>(this->mobile().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "wbapi.PushPrivateMsgRequest.mobile");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->mobile(), output);
  }

  // string msg = 3;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg().data(), static_cast<int>(this->msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "wbapi.PushPrivateMsgRequest.msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->msg(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.PushPrivateMsgRequest)
}

size_t PushPrivateMsgRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.PushPrivateMsgRequest)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string mobile = 2;
  if (this->mobile().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->mobile());
  }

  // string msg = 3;
  if (this->msg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->msg());
  }

  // int32 flag = 1;
  if (this->flag() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->flag());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PushPrivateMsgRequest::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const PushPrivateMsgRequest*>(&from));
}

void PushPrivateMsgRequest::MergeFrom(const PushPrivateMsgRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.PushPrivateMsgRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.mobile().size() > 0) {

    mobile_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mobile_);
  }
  if (from.msg().size() > 0) {

    msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_);
  }
  if (from.flag() != 0) {
    set_flag(from.flag());
  }
}

void PushPrivateMsgRequest::CopyFrom(const PushPrivateMsgRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.PushPrivateMsgRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PushPrivateMsgRequest::IsInitialized() const {
  return true;
}

void PushPrivateMsgRequest::Swap(PushPrivateMsgRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PushPrivateMsgRequest::InternalSwap(PushPrivateMsgRequest* other) {
  using std::swap;
  mobile_.Swap(&other->mobile_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  msg_.Swap(&other->msg_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(flag_, other->flag_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string PushPrivateMsgRequest::GetTypeName() const {
  return "wbapi.PushPrivateMsgRequest";
}


// ===================================================================

void PushPrivateMsgResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PushPrivateMsgResponse::kErrorCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PushPrivateMsgResponse::PushPrivateMsgResponse()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_push_2eproto::scc_info_PushPrivateMsgResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.PushPrivateMsgResponse)
}
PushPrivateMsgResponse::PushPrivateMsgResponse(const PushPrivateMsgResponse& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  error_code_ = from.error_code_;
  // @@protoc_insertion_point(copy_constructor:wbapi.PushPrivateMsgResponse)
}

void PushPrivateMsgResponse::SharedCtor() {
  error_code_ = 0;
}

PushPrivateMsgResponse::~PushPrivateMsgResponse() {
  // @@protoc_insertion_point(destructor:wbapi.PushPrivateMsgResponse)
  SharedDtor();
}

void PushPrivateMsgResponse::SharedDtor() {
}

void PushPrivateMsgResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PushPrivateMsgResponse& PushPrivateMsgResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_push_2eproto::scc_info_PushPrivateMsgResponse.base);
  return *internal_default_instance();
}


void PushPrivateMsgResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.PushPrivateMsgResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  error_code_ = 0;
  _internal_metadata_.Clear();
}

bool PushPrivateMsgResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.PushPrivateMsgResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 error_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.PushPrivateMsgResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.PushPrivateMsgResponse)
  return false;
#undef DO_
}

void PushPrivateMsgResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.PushPrivateMsgResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error_code(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.PushPrivateMsgResponse)
}

size_t PushPrivateMsgResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.PushPrivateMsgResponse)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error_code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PushPrivateMsgResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const PushPrivateMsgResponse*>(&from));
}

void PushPrivateMsgResponse::MergeFrom(const PushPrivateMsgResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.PushPrivateMsgResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.error_code() != 0) {
    set_error_code(from.error_code());
  }
}

void PushPrivateMsgResponse::CopyFrom(const PushPrivateMsgResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.PushPrivateMsgResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PushPrivateMsgResponse::IsInitialized() const {
  return true;
}

void PushPrivateMsgResponse::Swap(PushPrivateMsgResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PushPrivateMsgResponse::InternalSwap(PushPrivateMsgResponse* other) {
  using std::swap;
  swap(error_code_, other->error_code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string PushPrivateMsgResponse::GetTypeName() const {
  return "wbapi.PushPrivateMsgResponse";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace wbapi
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::BindPushTokenRequest* Arena::CreateMaybeMessage< ::wbapi::BindPushTokenRequest >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::BindPushTokenRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::BindPushTokenResponse* Arena::CreateMaybeMessage< ::wbapi::BindPushTokenResponse >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::BindPushTokenResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::PushSettingRequest* Arena::CreateMaybeMessage< ::wbapi::PushSettingRequest >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::PushSettingRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::PushSettingResponse* Arena::CreateMaybeMessage< ::wbapi::PushSettingResponse >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::PushSettingResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::GetPushSettingRequest* Arena::CreateMaybeMessage< ::wbapi::GetPushSettingRequest >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::GetPushSettingRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::GetPushSettingResponse* Arena::CreateMaybeMessage< ::wbapi::GetPushSettingResponse >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::GetPushSettingResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::DeviceAlarmOfflineMsg* Arena::CreateMaybeMessage< ::wbapi::DeviceAlarmOfflineMsg >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::DeviceAlarmOfflineMsg >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::PushPrivateMsgRequest* Arena::CreateMaybeMessage< ::wbapi::PushPrivateMsgRequest >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::PushPrivateMsgRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::PushPrivateMsgResponse* Arena::CreateMaybeMessage< ::wbapi::PushPrivateMsgResponse >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::PushPrivateMsgResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
