// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room_perm.proto

#ifndef PROTOBUF_INCLUDED_room_5fperm_2eproto
#define PROTOBUF_INCLUDED_room_5fperm_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
#include "basic.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_room_5fperm_2eproto 

namespace protobuf_room_5fperm_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[8];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
}  // namespace protobuf_room_5fperm_2eproto
namespace wbapi {
class DeleteRoomPermsRequest;
class DeleteRoomPermsRequestDefaultTypeInternal;
extern DeleteRoomPermsRequestDefaultTypeInternal _DeleteRoomPermsRequest_default_instance_;
class DeleteRoomPermsResponse;
class DeleteRoomPermsResponseDefaultTypeInternal;
extern DeleteRoomPermsResponseDefaultTypeInternal _DeleteRoomPermsResponse_default_instance_;
class ListRoomPermsRequest;
class ListRoomPermsRequestDefaultTypeInternal;
extern ListRoomPermsRequestDefaultTypeInternal _ListRoomPermsRequest_default_instance_;
class ListRoomPermsResponse;
class ListRoomPermsResponseDefaultTypeInternal;
extern ListRoomPermsResponseDefaultTypeInternal _ListRoomPermsResponse_default_instance_;
class RoomPerm;
class RoomPermDefaultTypeInternal;
extern RoomPermDefaultTypeInternal _RoomPerm_default_instance_;
class RoomPermsChangedNotification;
class RoomPermsChangedNotificationDefaultTypeInternal;
extern RoomPermsChangedNotificationDefaultTypeInternal _RoomPermsChangedNotification_default_instance_;
class SetRoomPermsRequest;
class SetRoomPermsRequestDefaultTypeInternal;
extern SetRoomPermsRequestDefaultTypeInternal _SetRoomPermsRequest_default_instance_;
class SetRoomPermsResponse;
class SetRoomPermsResponseDefaultTypeInternal;
extern SetRoomPermsResponseDefaultTypeInternal _SetRoomPermsResponse_default_instance_;
}  // namespace wbapi
namespace google {
namespace protobuf {
template<> ::wbapi::DeleteRoomPermsRequest* Arena::CreateMaybeMessage<::wbapi::DeleteRoomPermsRequest>(Arena*);
template<> ::wbapi::DeleteRoomPermsResponse* Arena::CreateMaybeMessage<::wbapi::DeleteRoomPermsResponse>(Arena*);
template<> ::wbapi::ListRoomPermsRequest* Arena::CreateMaybeMessage<::wbapi::ListRoomPermsRequest>(Arena*);
template<> ::wbapi::ListRoomPermsResponse* Arena::CreateMaybeMessage<::wbapi::ListRoomPermsResponse>(Arena*);
template<> ::wbapi::RoomPerm* Arena::CreateMaybeMessage<::wbapi::RoomPerm>(Arena*);
template<> ::wbapi::RoomPermsChangedNotification* Arena::CreateMaybeMessage<::wbapi::RoomPermsChangedNotification>(Arena*);
template<> ::wbapi::SetRoomPermsRequest* Arena::CreateMaybeMessage<::wbapi::SetRoomPermsRequest>(Arena*);
template<> ::wbapi::SetRoomPermsResponse* Arena::CreateMaybeMessage<::wbapi::SetRoomPermsResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace wbapi {

enum RoomPermEnum {
  NONE = 0,
  ALL = 1,
  RoomPermEnum_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  RoomPermEnum_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool RoomPermEnum_IsValid(int value);
const RoomPermEnum RoomPermEnum_MIN = NONE;
const RoomPermEnum RoomPermEnum_MAX = ALL;
const int RoomPermEnum_ARRAYSIZE = RoomPermEnum_MAX + 1;

// ===================================================================

class RoomPerm : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.RoomPerm) */ {
 public:
  RoomPerm();
  virtual ~RoomPerm();

  RoomPerm(const RoomPerm& from);

  inline RoomPerm& operator=(const RoomPerm& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoomPerm(RoomPerm&& from) noexcept
    : RoomPerm() {
    *this = ::std::move(from);
  }

  inline RoomPerm& operator=(RoomPerm&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const RoomPerm& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoomPerm* internal_default_instance() {
    return reinterpret_cast<const RoomPerm*>(
               &_RoomPerm_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(RoomPerm* other);
  friend void swap(RoomPerm& a, RoomPerm& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoomPerm* New() const final {
    return CreateMaybeMessage<RoomPerm>(NULL);
  }

  RoomPerm* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RoomPerm>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const RoomPerm& from);
  void MergeFrom(const RoomPerm& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RoomPerm* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string perm = 3;
  void clear_perm();
  static const int kPermFieldNumber = 3;
  const ::std::string& perm() const;
  void set_perm(const ::std::string& value);
  #if LANG_CXX11
  void set_perm(::std::string&& value);
  #endif
  void set_perm(const char* value);
  void set_perm(const char* value, size_t size);
  ::std::string* mutable_perm();
  ::std::string* release_perm();
  void set_allocated_perm(::std::string* perm);

  // string desc = 4;
  void clear_desc();
  static const int kDescFieldNumber = 4;
  const ::std::string& desc() const;
  void set_desc(const ::std::string& value);
  #if LANG_CXX11
  void set_desc(::std::string&& value);
  #endif
  void set_desc(const char* value);
  void set_desc(const char* value, size_t size);
  ::std::string* mutable_desc();
  ::std::string* release_desc();
  void set_allocated_desc(::std::string* desc);

  // int64 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::int64 user_id() const;
  void set_user_id(::google::protobuf::int64 value);

  // int32 room_id = 2;
  void clear_room_id();
  static const int kRoomIdFieldNumber = 2;
  ::google::protobuf::int32 room_id() const;
  void set_room_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wbapi.RoomPerm)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr perm_;
  ::google::protobuf::internal::ArenaStringPtr desc_;
  ::google::protobuf::int64 user_id_;
  ::google::protobuf::int32 room_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_room_5fperm_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SetRoomPermsRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.SetRoomPermsRequest) */ {
 public:
  SetRoomPermsRequest();
  virtual ~SetRoomPermsRequest();

  SetRoomPermsRequest(const SetRoomPermsRequest& from);

  inline SetRoomPermsRequest& operator=(const SetRoomPermsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SetRoomPermsRequest(SetRoomPermsRequest&& from) noexcept
    : SetRoomPermsRequest() {
    *this = ::std::move(from);
  }

  inline SetRoomPermsRequest& operator=(SetRoomPermsRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const SetRoomPermsRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SetRoomPermsRequest* internal_default_instance() {
    return reinterpret_cast<const SetRoomPermsRequest*>(
               &_SetRoomPermsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(SetRoomPermsRequest* other);
  friend void swap(SetRoomPermsRequest& a, SetRoomPermsRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SetRoomPermsRequest* New() const final {
    return CreateMaybeMessage<SetRoomPermsRequest>(NULL);
  }

  SetRoomPermsRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SetRoomPermsRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const SetRoomPermsRequest& from);
  void MergeFrom(const SetRoomPermsRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SetRoomPermsRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .wbapi.RoomPerm perms = 2;
  int perms_size() const;
  void clear_perms();
  static const int kPermsFieldNumber = 2;
  ::wbapi::RoomPerm* mutable_perms(int index);
  ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >*
      mutable_perms();
  const ::wbapi::RoomPerm& perms(int index) const;
  ::wbapi::RoomPerm* add_perms();
  const ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >&
      perms() const;

  // int32 family_id = 1;
  void clear_family_id();
  static const int kFamilyIdFieldNumber = 1;
  ::google::protobuf::int32 family_id() const;
  void set_family_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wbapi.SetRoomPermsRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm > perms_;
  ::google::protobuf::int32 family_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_room_5fperm_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SetRoomPermsResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.SetRoomPermsResponse) */ {
 public:
  SetRoomPermsResponse();
  virtual ~SetRoomPermsResponse();

  SetRoomPermsResponse(const SetRoomPermsResponse& from);

  inline SetRoomPermsResponse& operator=(const SetRoomPermsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SetRoomPermsResponse(SetRoomPermsResponse&& from) noexcept
    : SetRoomPermsResponse() {
    *this = ::std::move(from);
  }

  inline SetRoomPermsResponse& operator=(SetRoomPermsResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const SetRoomPermsResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SetRoomPermsResponse* internal_default_instance() {
    return reinterpret_cast<const SetRoomPermsResponse*>(
               &_SetRoomPermsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(SetRoomPermsResponse* other);
  friend void swap(SetRoomPermsResponse& a, SetRoomPermsResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SetRoomPermsResponse* New() const final {
    return CreateMaybeMessage<SetRoomPermsResponse>(NULL);
  }

  SetRoomPermsResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SetRoomPermsResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const SetRoomPermsResponse& from);
  void MergeFrom(const SetRoomPermsResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SetRoomPermsResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .wbapi.RoomPerm perms0 = 2;
  int perms0_size() const;
  void clear_perms0();
  static const int kPerms0FieldNumber = 2;
  ::wbapi::RoomPerm* mutable_perms0(int index);
  ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >*
      mutable_perms0();
  const ::wbapi::RoomPerm& perms0(int index) const;
  ::wbapi::RoomPerm* add_perms0();
  const ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >&
      perms0() const;

  // repeated .wbapi.RoomPerm perms1 = 3;
  int perms1_size() const;
  void clear_perms1();
  static const int kPerms1FieldNumber = 3;
  ::wbapi::RoomPerm* mutable_perms1(int index);
  ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >*
      mutable_perms1();
  const ::wbapi::RoomPerm& perms1(int index) const;
  ::wbapi::RoomPerm* add_perms1();
  const ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >&
      perms1() const;

  // int32 error_code = 1;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 error_code() const;
  void set_error_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wbapi.SetRoomPermsResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm > perms0_;
  ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm > perms1_;
  ::google::protobuf::int32 error_code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_room_5fperm_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RoomPermsChangedNotification : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.RoomPermsChangedNotification) */ {
 public:
  RoomPermsChangedNotification();
  virtual ~RoomPermsChangedNotification();

  RoomPermsChangedNotification(const RoomPermsChangedNotification& from);

  inline RoomPermsChangedNotification& operator=(const RoomPermsChangedNotification& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoomPermsChangedNotification(RoomPermsChangedNotification&& from) noexcept
    : RoomPermsChangedNotification() {
    *this = ::std::move(from);
  }

  inline RoomPermsChangedNotification& operator=(RoomPermsChangedNotification&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const RoomPermsChangedNotification& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoomPermsChangedNotification* internal_default_instance() {
    return reinterpret_cast<const RoomPermsChangedNotification*>(
               &_RoomPermsChangedNotification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(RoomPermsChangedNotification* other);
  friend void swap(RoomPermsChangedNotification& a, RoomPermsChangedNotification& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoomPermsChangedNotification* New() const final {
    return CreateMaybeMessage<RoomPermsChangedNotification>(NULL);
  }

  RoomPermsChangedNotification* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RoomPermsChangedNotification>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const RoomPermsChangedNotification& from);
  void MergeFrom(const RoomPermsChangedNotification& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RoomPermsChangedNotification* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 family_id = 1;
  void clear_family_id();
  static const int kFamilyIdFieldNumber = 1;
  ::google::protobuf::int32 family_id() const;
  void set_family_id(::google::protobuf::int32 value);

  // int32 room_id = 2;
  void clear_room_id();
  static const int kRoomIdFieldNumber = 2;
  ::google::protobuf::int32 room_id() const;
  void set_room_id(::google::protobuf::int32 value);

  // int64 user_id = 3;
  void clear_user_id();
  static const int kUserIdFieldNumber = 3;
  ::google::protobuf::int64 user_id() const;
  void set_user_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:wbapi.RoomPermsChangedNotification)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::int32 family_id_;
  ::google::protobuf::int32 room_id_;
  ::google::protobuf::int64 user_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_room_5fperm_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ListRoomPermsRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.ListRoomPermsRequest) */ {
 public:
  ListRoomPermsRequest();
  virtual ~ListRoomPermsRequest();

  ListRoomPermsRequest(const ListRoomPermsRequest& from);

  inline ListRoomPermsRequest& operator=(const ListRoomPermsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ListRoomPermsRequest(ListRoomPermsRequest&& from) noexcept
    : ListRoomPermsRequest() {
    *this = ::std::move(from);
  }

  inline ListRoomPermsRequest& operator=(ListRoomPermsRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ListRoomPermsRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ListRoomPermsRequest* internal_default_instance() {
    return reinterpret_cast<const ListRoomPermsRequest*>(
               &_ListRoomPermsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(ListRoomPermsRequest* other);
  friend void swap(ListRoomPermsRequest& a, ListRoomPermsRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ListRoomPermsRequest* New() const final {
    return CreateMaybeMessage<ListRoomPermsRequest>(NULL);
  }

  ListRoomPermsRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ListRoomPermsRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const ListRoomPermsRequest& from);
  void MergeFrom(const ListRoomPermsRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ListRoomPermsRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 family_id = 1;
  void clear_family_id();
  static const int kFamilyIdFieldNumber = 1;
  ::google::protobuf::int32 family_id() const;
  void set_family_id(::google::protobuf::int32 value);

  // int32 room_id = 2;
  void clear_room_id();
  static const int kRoomIdFieldNumber = 2;
  ::google::protobuf::int32 room_id() const;
  void set_room_id(::google::protobuf::int32 value);

  // int64 user_id = 3;
  void clear_user_id();
  static const int kUserIdFieldNumber = 3;
  ::google::protobuf::int64 user_id() const;
  void set_user_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:wbapi.ListRoomPermsRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::int32 family_id_;
  ::google::protobuf::int32 room_id_;
  ::google::protobuf::int64 user_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_room_5fperm_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ListRoomPermsResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.ListRoomPermsResponse) */ {
 public:
  ListRoomPermsResponse();
  virtual ~ListRoomPermsResponse();

  ListRoomPermsResponse(const ListRoomPermsResponse& from);

  inline ListRoomPermsResponse& operator=(const ListRoomPermsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ListRoomPermsResponse(ListRoomPermsResponse&& from) noexcept
    : ListRoomPermsResponse() {
    *this = ::std::move(from);
  }

  inline ListRoomPermsResponse& operator=(ListRoomPermsResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ListRoomPermsResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ListRoomPermsResponse* internal_default_instance() {
    return reinterpret_cast<const ListRoomPermsResponse*>(
               &_ListRoomPermsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(ListRoomPermsResponse* other);
  friend void swap(ListRoomPermsResponse& a, ListRoomPermsResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ListRoomPermsResponse* New() const final {
    return CreateMaybeMessage<ListRoomPermsResponse>(NULL);
  }

  ListRoomPermsResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ListRoomPermsResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const ListRoomPermsResponse& from);
  void MergeFrom(const ListRoomPermsResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ListRoomPermsResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .wbapi.RoomPerm perms = 6;
  int perms_size() const;
  void clear_perms();
  static const int kPermsFieldNumber = 6;
  ::wbapi::RoomPerm* mutable_perms(int index);
  ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >*
      mutable_perms();
  const ::wbapi::RoomPerm& perms(int index) const;
  ::wbapi::RoomPerm* add_perms();
  const ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >&
      perms() const;

  // int32 error_code = 1;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 error_code() const;
  void set_error_code(::google::protobuf::int32 value);

  // int32 family_id = 2;
  void clear_family_id();
  static const int kFamilyIdFieldNumber = 2;
  ::google::protobuf::int32 family_id() const;
  void set_family_id(::google::protobuf::int32 value);

  // int64 user_id = 4;
  void clear_user_id();
  static const int kUserIdFieldNumber = 4;
  ::google::protobuf::int64 user_id() const;
  void set_user_id(::google::protobuf::int64 value);

  // int32 room_id = 3;
  void clear_room_id();
  static const int kRoomIdFieldNumber = 3;
  ::google::protobuf::int32 room_id() const;
  void set_room_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wbapi.ListRoomPermsResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm > perms_;
  ::google::protobuf::int32 error_code_;
  ::google::protobuf::int32 family_id_;
  ::google::protobuf::int64 user_id_;
  ::google::protobuf::int32 room_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_room_5fperm_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeleteRoomPermsRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.DeleteRoomPermsRequest) */ {
 public:
  DeleteRoomPermsRequest();
  virtual ~DeleteRoomPermsRequest();

  DeleteRoomPermsRequest(const DeleteRoomPermsRequest& from);

  inline DeleteRoomPermsRequest& operator=(const DeleteRoomPermsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeleteRoomPermsRequest(DeleteRoomPermsRequest&& from) noexcept
    : DeleteRoomPermsRequest() {
    *this = ::std::move(from);
  }

  inline DeleteRoomPermsRequest& operator=(DeleteRoomPermsRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const DeleteRoomPermsRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeleteRoomPermsRequest* internal_default_instance() {
    return reinterpret_cast<const DeleteRoomPermsRequest*>(
               &_DeleteRoomPermsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(DeleteRoomPermsRequest* other);
  friend void swap(DeleteRoomPermsRequest& a, DeleteRoomPermsRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeleteRoomPermsRequest* New() const final {
    return CreateMaybeMessage<DeleteRoomPermsRequest>(NULL);
  }

  DeleteRoomPermsRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeleteRoomPermsRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const DeleteRoomPermsRequest& from);
  void MergeFrom(const DeleteRoomPermsRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DeleteRoomPermsRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 family_id = 1;
  void clear_family_id();
  static const int kFamilyIdFieldNumber = 1;
  ::google::protobuf::int32 family_id() const;
  void set_family_id(::google::protobuf::int32 value);

  // int32 room_id = 2;
  void clear_room_id();
  static const int kRoomIdFieldNumber = 2;
  ::google::protobuf::int32 room_id() const;
  void set_room_id(::google::protobuf::int32 value);

  // int64 user_id = 3;
  void clear_user_id();
  static const int kUserIdFieldNumber = 3;
  ::google::protobuf::int64 user_id() const;
  void set_user_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:wbapi.DeleteRoomPermsRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::int32 family_id_;
  ::google::protobuf::int32 room_id_;
  ::google::protobuf::int64 user_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_room_5fperm_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeleteRoomPermsResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:wbapi.DeleteRoomPermsResponse) */ {
 public:
  DeleteRoomPermsResponse();
  virtual ~DeleteRoomPermsResponse();

  DeleteRoomPermsResponse(const DeleteRoomPermsResponse& from);

  inline DeleteRoomPermsResponse& operator=(const DeleteRoomPermsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeleteRoomPermsResponse(DeleteRoomPermsResponse&& from) noexcept
    : DeleteRoomPermsResponse() {
    *this = ::std::move(from);
  }

  inline DeleteRoomPermsResponse& operator=(DeleteRoomPermsResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const DeleteRoomPermsResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeleteRoomPermsResponse* internal_default_instance() {
    return reinterpret_cast<const DeleteRoomPermsResponse*>(
               &_DeleteRoomPermsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(DeleteRoomPermsResponse* other);
  friend void swap(DeleteRoomPermsResponse& a, DeleteRoomPermsResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeleteRoomPermsResponse* New() const final {
    return CreateMaybeMessage<DeleteRoomPermsResponse>(NULL);
  }

  DeleteRoomPermsResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeleteRoomPermsResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const DeleteRoomPermsResponse& from);
  void MergeFrom(const DeleteRoomPermsResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DeleteRoomPermsResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 error_code = 1;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 error_code() const;
  void set_error_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wbapi.DeleteRoomPermsResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::int32 error_code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_room_5fperm_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RoomPerm

// int64 user_id = 1;
inline void RoomPerm::clear_user_id() {
  user_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 RoomPerm::user_id() const {
  // @@protoc_insertion_point(field_get:wbapi.RoomPerm.user_id)
  return user_id_;
}
inline void RoomPerm::set_user_id(::google::protobuf::int64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.RoomPerm.user_id)
}

// int32 room_id = 2;
inline void RoomPerm::clear_room_id() {
  room_id_ = 0;
}
inline ::google::protobuf::int32 RoomPerm::room_id() const {
  // @@protoc_insertion_point(field_get:wbapi.RoomPerm.room_id)
  return room_id_;
}
inline void RoomPerm::set_room_id(::google::protobuf::int32 value) {
  
  room_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.RoomPerm.room_id)
}

// string perm = 3;
inline void RoomPerm::clear_perm() {
  perm_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RoomPerm::perm() const {
  // @@protoc_insertion_point(field_get:wbapi.RoomPerm.perm)
  return perm_.GetNoArena();
}
inline void RoomPerm::set_perm(const ::std::string& value) {
  
  perm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:wbapi.RoomPerm.perm)
}
#if LANG_CXX11
inline void RoomPerm::set_perm(::std::string&& value) {
  
  perm_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:wbapi.RoomPerm.perm)
}
#endif
inline void RoomPerm::set_perm(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  perm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:wbapi.RoomPerm.perm)
}
inline void RoomPerm::set_perm(const char* value, size_t size) {
  
  perm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:wbapi.RoomPerm.perm)
}
inline ::std::string* RoomPerm::mutable_perm() {
  
  // @@protoc_insertion_point(field_mutable:wbapi.RoomPerm.perm)
  return perm_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoomPerm::release_perm() {
  // @@protoc_insertion_point(field_release:wbapi.RoomPerm.perm)
  
  return perm_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoomPerm::set_allocated_perm(::std::string* perm) {
  if (perm != NULL) {
    
  } else {
    
  }
  perm_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), perm);
  // @@protoc_insertion_point(field_set_allocated:wbapi.RoomPerm.perm)
}

// string desc = 4;
inline void RoomPerm::clear_desc() {
  desc_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RoomPerm::desc() const {
  // @@protoc_insertion_point(field_get:wbapi.RoomPerm.desc)
  return desc_.GetNoArena();
}
inline void RoomPerm::set_desc(const ::std::string& value) {
  
  desc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:wbapi.RoomPerm.desc)
}
#if LANG_CXX11
inline void RoomPerm::set_desc(::std::string&& value) {
  
  desc_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:wbapi.RoomPerm.desc)
}
#endif
inline void RoomPerm::set_desc(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  desc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:wbapi.RoomPerm.desc)
}
inline void RoomPerm::set_desc(const char* value, size_t size) {
  
  desc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:wbapi.RoomPerm.desc)
}
inline ::std::string* RoomPerm::mutable_desc() {
  
  // @@protoc_insertion_point(field_mutable:wbapi.RoomPerm.desc)
  return desc_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoomPerm::release_desc() {
  // @@protoc_insertion_point(field_release:wbapi.RoomPerm.desc)
  
  return desc_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoomPerm::set_allocated_desc(::std::string* desc) {
  if (desc != NULL) {
    
  } else {
    
  }
  desc_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), desc);
  // @@protoc_insertion_point(field_set_allocated:wbapi.RoomPerm.desc)
}

// -------------------------------------------------------------------

// SetRoomPermsRequest

// int32 family_id = 1;
inline void SetRoomPermsRequest::clear_family_id() {
  family_id_ = 0;
}
inline ::google::protobuf::int32 SetRoomPermsRequest::family_id() const {
  // @@protoc_insertion_point(field_get:wbapi.SetRoomPermsRequest.family_id)
  return family_id_;
}
inline void SetRoomPermsRequest::set_family_id(::google::protobuf::int32 value) {
  
  family_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.SetRoomPermsRequest.family_id)
}

// repeated .wbapi.RoomPerm perms = 2;
inline int SetRoomPermsRequest::perms_size() const {
  return perms_.size();
}
inline void SetRoomPermsRequest::clear_perms() {
  perms_.Clear();
}
inline ::wbapi::RoomPerm* SetRoomPermsRequest::mutable_perms(int index) {
  // @@protoc_insertion_point(field_mutable:wbapi.SetRoomPermsRequest.perms)
  return perms_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >*
SetRoomPermsRequest::mutable_perms() {
  // @@protoc_insertion_point(field_mutable_list:wbapi.SetRoomPermsRequest.perms)
  return &perms_;
}
inline const ::wbapi::RoomPerm& SetRoomPermsRequest::perms(int index) const {
  // @@protoc_insertion_point(field_get:wbapi.SetRoomPermsRequest.perms)
  return perms_.Get(index);
}
inline ::wbapi::RoomPerm* SetRoomPermsRequest::add_perms() {
  // @@protoc_insertion_point(field_add:wbapi.SetRoomPermsRequest.perms)
  return perms_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >&
SetRoomPermsRequest::perms() const {
  // @@protoc_insertion_point(field_list:wbapi.SetRoomPermsRequest.perms)
  return perms_;
}

// -------------------------------------------------------------------

// SetRoomPermsResponse

// int32 error_code = 1;
inline void SetRoomPermsResponse::clear_error_code() {
  error_code_ = 0;
}
inline ::google::protobuf::int32 SetRoomPermsResponse::error_code() const {
  // @@protoc_insertion_point(field_get:wbapi.SetRoomPermsResponse.error_code)
  return error_code_;
}
inline void SetRoomPermsResponse::set_error_code(::google::protobuf::int32 value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:wbapi.SetRoomPermsResponse.error_code)
}

// repeated .wbapi.RoomPerm perms0 = 2;
inline int SetRoomPermsResponse::perms0_size() const {
  return perms0_.size();
}
inline void SetRoomPermsResponse::clear_perms0() {
  perms0_.Clear();
}
inline ::wbapi::RoomPerm* SetRoomPermsResponse::mutable_perms0(int index) {
  // @@protoc_insertion_point(field_mutable:wbapi.SetRoomPermsResponse.perms0)
  return perms0_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >*
SetRoomPermsResponse::mutable_perms0() {
  // @@protoc_insertion_point(field_mutable_list:wbapi.SetRoomPermsResponse.perms0)
  return &perms0_;
}
inline const ::wbapi::RoomPerm& SetRoomPermsResponse::perms0(int index) const {
  // @@protoc_insertion_point(field_get:wbapi.SetRoomPermsResponse.perms0)
  return perms0_.Get(index);
}
inline ::wbapi::RoomPerm* SetRoomPermsResponse::add_perms0() {
  // @@protoc_insertion_point(field_add:wbapi.SetRoomPermsResponse.perms0)
  return perms0_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >&
SetRoomPermsResponse::perms0() const {
  // @@protoc_insertion_point(field_list:wbapi.SetRoomPermsResponse.perms0)
  return perms0_;
}

// repeated .wbapi.RoomPerm perms1 = 3;
inline int SetRoomPermsResponse::perms1_size() const {
  return perms1_.size();
}
inline void SetRoomPermsResponse::clear_perms1() {
  perms1_.Clear();
}
inline ::wbapi::RoomPerm* SetRoomPermsResponse::mutable_perms1(int index) {
  // @@protoc_insertion_point(field_mutable:wbapi.SetRoomPermsResponse.perms1)
  return perms1_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >*
SetRoomPermsResponse::mutable_perms1() {
  // @@protoc_insertion_point(field_mutable_list:wbapi.SetRoomPermsResponse.perms1)
  return &perms1_;
}
inline const ::wbapi::RoomPerm& SetRoomPermsResponse::perms1(int index) const {
  // @@protoc_insertion_point(field_get:wbapi.SetRoomPermsResponse.perms1)
  return perms1_.Get(index);
}
inline ::wbapi::RoomPerm* SetRoomPermsResponse::add_perms1() {
  // @@protoc_insertion_point(field_add:wbapi.SetRoomPermsResponse.perms1)
  return perms1_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >&
SetRoomPermsResponse::perms1() const {
  // @@protoc_insertion_point(field_list:wbapi.SetRoomPermsResponse.perms1)
  return perms1_;
}

// -------------------------------------------------------------------

// RoomPermsChangedNotification

// int32 family_id = 1;
inline void RoomPermsChangedNotification::clear_family_id() {
  family_id_ = 0;
}
inline ::google::protobuf::int32 RoomPermsChangedNotification::family_id() const {
  // @@protoc_insertion_point(field_get:wbapi.RoomPermsChangedNotification.family_id)
  return family_id_;
}
inline void RoomPermsChangedNotification::set_family_id(::google::protobuf::int32 value) {
  
  family_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.RoomPermsChangedNotification.family_id)
}

// int32 room_id = 2;
inline void RoomPermsChangedNotification::clear_room_id() {
  room_id_ = 0;
}
inline ::google::protobuf::int32 RoomPermsChangedNotification::room_id() const {
  // @@protoc_insertion_point(field_get:wbapi.RoomPermsChangedNotification.room_id)
  return room_id_;
}
inline void RoomPermsChangedNotification::set_room_id(::google::protobuf::int32 value) {
  
  room_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.RoomPermsChangedNotification.room_id)
}

// int64 user_id = 3;
inline void RoomPermsChangedNotification::clear_user_id() {
  user_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 RoomPermsChangedNotification::user_id() const {
  // @@protoc_insertion_point(field_get:wbapi.RoomPermsChangedNotification.user_id)
  return user_id_;
}
inline void RoomPermsChangedNotification::set_user_id(::google::protobuf::int64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.RoomPermsChangedNotification.user_id)
}

// -------------------------------------------------------------------

// ListRoomPermsRequest

// int32 family_id = 1;
inline void ListRoomPermsRequest::clear_family_id() {
  family_id_ = 0;
}
inline ::google::protobuf::int32 ListRoomPermsRequest::family_id() const {
  // @@protoc_insertion_point(field_get:wbapi.ListRoomPermsRequest.family_id)
  return family_id_;
}
inline void ListRoomPermsRequest::set_family_id(::google::protobuf::int32 value) {
  
  family_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.ListRoomPermsRequest.family_id)
}

// int32 room_id = 2;
inline void ListRoomPermsRequest::clear_room_id() {
  room_id_ = 0;
}
inline ::google::protobuf::int32 ListRoomPermsRequest::room_id() const {
  // @@protoc_insertion_point(field_get:wbapi.ListRoomPermsRequest.room_id)
  return room_id_;
}
inline void ListRoomPermsRequest::set_room_id(::google::protobuf::int32 value) {
  
  room_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.ListRoomPermsRequest.room_id)
}

// int64 user_id = 3;
inline void ListRoomPermsRequest::clear_user_id() {
  user_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 ListRoomPermsRequest::user_id() const {
  // @@protoc_insertion_point(field_get:wbapi.ListRoomPermsRequest.user_id)
  return user_id_;
}
inline void ListRoomPermsRequest::set_user_id(::google::protobuf::int64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.ListRoomPermsRequest.user_id)
}

// -------------------------------------------------------------------

// ListRoomPermsResponse

// int32 error_code = 1;
inline void ListRoomPermsResponse::clear_error_code() {
  error_code_ = 0;
}
inline ::google::protobuf::int32 ListRoomPermsResponse::error_code() const {
  // @@protoc_insertion_point(field_get:wbapi.ListRoomPermsResponse.error_code)
  return error_code_;
}
inline void ListRoomPermsResponse::set_error_code(::google::protobuf::int32 value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:wbapi.ListRoomPermsResponse.error_code)
}

// int32 family_id = 2;
inline void ListRoomPermsResponse::clear_family_id() {
  family_id_ = 0;
}
inline ::google::protobuf::int32 ListRoomPermsResponse::family_id() const {
  // @@protoc_insertion_point(field_get:wbapi.ListRoomPermsResponse.family_id)
  return family_id_;
}
inline void ListRoomPermsResponse::set_family_id(::google::protobuf::int32 value) {
  
  family_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.ListRoomPermsResponse.family_id)
}

// int32 room_id = 3;
inline void ListRoomPermsResponse::clear_room_id() {
  room_id_ = 0;
}
inline ::google::protobuf::int32 ListRoomPermsResponse::room_id() const {
  // @@protoc_insertion_point(field_get:wbapi.ListRoomPermsResponse.room_id)
  return room_id_;
}
inline void ListRoomPermsResponse::set_room_id(::google::protobuf::int32 value) {
  
  room_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.ListRoomPermsResponse.room_id)
}

// int64 user_id = 4;
inline void ListRoomPermsResponse::clear_user_id() {
  user_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 ListRoomPermsResponse::user_id() const {
  // @@protoc_insertion_point(field_get:wbapi.ListRoomPermsResponse.user_id)
  return user_id_;
}
inline void ListRoomPermsResponse::set_user_id(::google::protobuf::int64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.ListRoomPermsResponse.user_id)
}

// repeated .wbapi.RoomPerm perms = 6;
inline int ListRoomPermsResponse::perms_size() const {
  return perms_.size();
}
inline void ListRoomPermsResponse::clear_perms() {
  perms_.Clear();
}
inline ::wbapi::RoomPerm* ListRoomPermsResponse::mutable_perms(int index) {
  // @@protoc_insertion_point(field_mutable:wbapi.ListRoomPermsResponse.perms)
  return perms_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >*
ListRoomPermsResponse::mutable_perms() {
  // @@protoc_insertion_point(field_mutable_list:wbapi.ListRoomPermsResponse.perms)
  return &perms_;
}
inline const ::wbapi::RoomPerm& ListRoomPermsResponse::perms(int index) const {
  // @@protoc_insertion_point(field_get:wbapi.ListRoomPermsResponse.perms)
  return perms_.Get(index);
}
inline ::wbapi::RoomPerm* ListRoomPermsResponse::add_perms() {
  // @@protoc_insertion_point(field_add:wbapi.ListRoomPermsResponse.perms)
  return perms_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::wbapi::RoomPerm >&
ListRoomPermsResponse::perms() const {
  // @@protoc_insertion_point(field_list:wbapi.ListRoomPermsResponse.perms)
  return perms_;
}

// -------------------------------------------------------------------

// DeleteRoomPermsRequest

// int32 family_id = 1;
inline void DeleteRoomPermsRequest::clear_family_id() {
  family_id_ = 0;
}
inline ::google::protobuf::int32 DeleteRoomPermsRequest::family_id() const {
  // @@protoc_insertion_point(field_get:wbapi.DeleteRoomPermsRequest.family_id)
  return family_id_;
}
inline void DeleteRoomPermsRequest::set_family_id(::google::protobuf::int32 value) {
  
  family_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.DeleteRoomPermsRequest.family_id)
}

// int32 room_id = 2;
inline void DeleteRoomPermsRequest::clear_room_id() {
  room_id_ = 0;
}
inline ::google::protobuf::int32 DeleteRoomPermsRequest::room_id() const {
  // @@protoc_insertion_point(field_get:wbapi.DeleteRoomPermsRequest.room_id)
  return room_id_;
}
inline void DeleteRoomPermsRequest::set_room_id(::google::protobuf::int32 value) {
  
  room_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.DeleteRoomPermsRequest.room_id)
}

// int64 user_id = 3;
inline void DeleteRoomPermsRequest::clear_user_id() {
  user_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 DeleteRoomPermsRequest::user_id() const {
  // @@protoc_insertion_point(field_get:wbapi.DeleteRoomPermsRequest.user_id)
  return user_id_;
}
inline void DeleteRoomPermsRequest::set_user_id(::google::protobuf::int64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:wbapi.DeleteRoomPermsRequest.user_id)
}

// -------------------------------------------------------------------

// DeleteRoomPermsResponse

// int32 error_code = 1;
inline void DeleteRoomPermsResponse::clear_error_code() {
  error_code_ = 0;
}
inline ::google::protobuf::int32 DeleteRoomPermsResponse::error_code() const {
  // @@protoc_insertion_point(field_get:wbapi.DeleteRoomPermsResponse.error_code)
  return error_code_;
}
inline void DeleteRoomPermsResponse::set_error_code(::google::protobuf::int32 value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:wbapi.DeleteRoomPermsResponse.error_code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace wbapi

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::wbapi::RoomPermEnum> : ::std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_room_5fperm_2eproto
