// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room_perm.proto

#include "room_perm.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_room_5fperm_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_room_5fperm_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_RoomPerm;
}  // namespace protobuf_room_5fperm_2eproto
namespace wbapi {
class RoomPermDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RoomPerm>
      _instance;
} _RoomPerm_default_instance_;
class SetRoomPermsRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SetRoomPermsRequest>
      _instance;
} _SetRoomPermsRequest_default_instance_;
class SetRoomPermsResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SetRoomPermsResponse>
      _instance;
} _SetRoomPermsResponse_default_instance_;
class RoomPermsChangedNotificationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RoomPermsChangedNotification>
      _instance;
} _RoomPermsChangedNotification_default_instance_;
class ListRoomPermsRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ListRoomPermsRequest>
      _instance;
} _ListRoomPermsRequest_default_instance_;
class ListRoomPermsResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ListRoomPermsResponse>
      _instance;
} _ListRoomPermsResponse_default_instance_;
class DeleteRoomPermsRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DeleteRoomPermsRequest>
      _instance;
} _DeleteRoomPermsRequest_default_instance_;
class DeleteRoomPermsResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DeleteRoomPermsResponse>
      _instance;
} _DeleteRoomPermsResponse_default_instance_;
}  // namespace wbapi
namespace protobuf_room_5fperm_2eproto {
static void InitDefaultsRoomPerm() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_RoomPerm_default_instance_;
    new (ptr) ::wbapi::RoomPerm();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::RoomPerm::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RoomPerm =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRoomPerm}, {}};

static void InitDefaultsSetRoomPermsRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_SetRoomPermsRequest_default_instance_;
    new (ptr) ::wbapi::SetRoomPermsRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::SetRoomPermsRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_SetRoomPermsRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsSetRoomPermsRequest}, {
      &protobuf_room_5fperm_2eproto::scc_info_RoomPerm.base,}};

static void InitDefaultsSetRoomPermsResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_SetRoomPermsResponse_default_instance_;
    new (ptr) ::wbapi::SetRoomPermsResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::SetRoomPermsResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_SetRoomPermsResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsSetRoomPermsResponse}, {
      &protobuf_room_5fperm_2eproto::scc_info_RoomPerm.base,}};

static void InitDefaultsRoomPermsChangedNotification() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_RoomPermsChangedNotification_default_instance_;
    new (ptr) ::wbapi::RoomPermsChangedNotification();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::RoomPermsChangedNotification::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RoomPermsChangedNotification =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRoomPermsChangedNotification}, {}};

static void InitDefaultsListRoomPermsRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_ListRoomPermsRequest_default_instance_;
    new (ptr) ::wbapi::ListRoomPermsRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::ListRoomPermsRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ListRoomPermsRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsListRoomPermsRequest}, {}};

static void InitDefaultsListRoomPermsResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_ListRoomPermsResponse_default_instance_;
    new (ptr) ::wbapi::ListRoomPermsResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::ListRoomPermsResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ListRoomPermsResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsListRoomPermsResponse}, {
      &protobuf_room_5fperm_2eproto::scc_info_RoomPerm.base,}};

static void InitDefaultsDeleteRoomPermsRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_DeleteRoomPermsRequest_default_instance_;
    new (ptr) ::wbapi::DeleteRoomPermsRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::DeleteRoomPermsRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DeleteRoomPermsRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDeleteRoomPermsRequest}, {}};

static void InitDefaultsDeleteRoomPermsResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::wbapi::_DeleteRoomPermsResponse_default_instance_;
    new (ptr) ::wbapi::DeleteRoomPermsResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::wbapi::DeleteRoomPermsResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DeleteRoomPermsResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDeleteRoomPermsResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_RoomPerm.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SetRoomPermsRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SetRoomPermsResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_RoomPermsChangedNotification.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ListRoomPermsRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ListRoomPermsResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DeleteRoomPermsRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DeleteRoomPermsResponse.base);
}

}  // namespace protobuf_room_5fperm_2eproto
namespace wbapi {
bool RoomPermEnum_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void RoomPerm::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RoomPerm::kUserIdFieldNumber;
const int RoomPerm::kRoomIdFieldNumber;
const int RoomPerm::kPermFieldNumber;
const int RoomPerm::kDescFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RoomPerm::RoomPerm()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_room_5fperm_2eproto::scc_info_RoomPerm.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.RoomPerm)
}
RoomPerm::RoomPerm(const RoomPerm& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  perm_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.perm().size() > 0) {
    perm_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.perm_);
  }
  desc_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.desc().size() > 0) {
    desc_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.desc_);
  }
  ::memcpy(&user_id_, &from.user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&room_id_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(room_id_));
  // @@protoc_insertion_point(copy_constructor:wbapi.RoomPerm)
}

void RoomPerm::SharedCtor() {
  perm_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  desc_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&room_id_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(room_id_));
}

RoomPerm::~RoomPerm() {
  // @@protoc_insertion_point(destructor:wbapi.RoomPerm)
  SharedDtor();
}

void RoomPerm::SharedDtor() {
  perm_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  desc_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RoomPerm::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RoomPerm& RoomPerm::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_room_5fperm_2eproto::scc_info_RoomPerm.base);
  return *internal_default_instance();
}


void RoomPerm::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.RoomPerm)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  perm_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  desc_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&room_id_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(room_id_));
  _internal_metadata_.Clear();
}

bool RoomPerm::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.RoomPerm)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 user_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &user_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 room_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &room_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string perm = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_perm()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->perm().data(), static_cast<int>(this->perm().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "wbapi.RoomPerm.perm"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string desc = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_desc()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->desc().data(), static_cast<int>(this->desc().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "wbapi.RoomPerm.desc"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.RoomPerm)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.RoomPerm)
  return false;
#undef DO_
}

void RoomPerm::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.RoomPerm)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 user_id = 1;
  if (this->user_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->user_id(), output);
  }

  // int32 room_id = 2;
  if (this->room_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->room_id(), output);
  }

  // string perm = 3;
  if (this->perm().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->perm().data(), static_cast<int>(this->perm().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "wbapi.RoomPerm.perm");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->perm(), output);
  }

  // string desc = 4;
  if (this->desc().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->desc().data(), static_cast<int>(this->desc().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "wbapi.RoomPerm.desc");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->desc(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.RoomPerm)
}

size_t RoomPerm::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.RoomPerm)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string perm = 3;
  if (this->perm().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->perm());
  }

  // string desc = 4;
  if (this->desc().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->desc());
  }

  // int64 user_id = 1;
  if (this->user_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->user_id());
  }

  // int32 room_id = 2;
  if (this->room_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->room_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RoomPerm::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const RoomPerm*>(&from));
}

void RoomPerm::MergeFrom(const RoomPerm& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.RoomPerm)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.perm().size() > 0) {

    perm_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.perm_);
  }
  if (from.desc().size() > 0) {

    desc_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.desc_);
  }
  if (from.user_id() != 0) {
    set_user_id(from.user_id());
  }
  if (from.room_id() != 0) {
    set_room_id(from.room_id());
  }
}

void RoomPerm::CopyFrom(const RoomPerm& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.RoomPerm)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RoomPerm::IsInitialized() const {
  return true;
}

void RoomPerm::Swap(RoomPerm* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RoomPerm::InternalSwap(RoomPerm* other) {
  using std::swap;
  perm_.Swap(&other->perm_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  desc_.Swap(&other->desc_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(user_id_, other->user_id_);
  swap(room_id_, other->room_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string RoomPerm::GetTypeName() const {
  return "wbapi.RoomPerm";
}


// ===================================================================

void SetRoomPermsRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SetRoomPermsRequest::kFamilyIdFieldNumber;
const int SetRoomPermsRequest::kPermsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SetRoomPermsRequest::SetRoomPermsRequest()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_room_5fperm_2eproto::scc_info_SetRoomPermsRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.SetRoomPermsRequest)
}
SetRoomPermsRequest::SetRoomPermsRequest(const SetRoomPermsRequest& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      perms_(from.perms_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  family_id_ = from.family_id_;
  // @@protoc_insertion_point(copy_constructor:wbapi.SetRoomPermsRequest)
}

void SetRoomPermsRequest::SharedCtor() {
  family_id_ = 0;
}

SetRoomPermsRequest::~SetRoomPermsRequest() {
  // @@protoc_insertion_point(destructor:wbapi.SetRoomPermsRequest)
  SharedDtor();
}

void SetRoomPermsRequest::SharedDtor() {
}

void SetRoomPermsRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SetRoomPermsRequest& SetRoomPermsRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_room_5fperm_2eproto::scc_info_SetRoomPermsRequest.base);
  return *internal_default_instance();
}


void SetRoomPermsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.SetRoomPermsRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  perms_.Clear();
  family_id_ = 0;
  _internal_metadata_.Clear();
}

bool SetRoomPermsRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.SetRoomPermsRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 family_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &family_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .wbapi.RoomPerm perms = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_perms()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.SetRoomPermsRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.SetRoomPermsRequest)
  return false;
#undef DO_
}

void SetRoomPermsRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.SetRoomPermsRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 family_id = 1;
  if (this->family_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->family_id(), output);
  }

  // repeated .wbapi.RoomPerm perms = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->perms_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2,
      this->perms(static_cast<int>(i)),
      output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.SetRoomPermsRequest)
}

size_t SetRoomPermsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.SetRoomPermsRequest)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // repeated .wbapi.RoomPerm perms = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->perms_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->perms(static_cast<int>(i)));
    }
  }

  // int32 family_id = 1;
  if (this->family_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->family_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SetRoomPermsRequest::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const SetRoomPermsRequest*>(&from));
}

void SetRoomPermsRequest::MergeFrom(const SetRoomPermsRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.SetRoomPermsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  perms_.MergeFrom(from.perms_);
  if (from.family_id() != 0) {
    set_family_id(from.family_id());
  }
}

void SetRoomPermsRequest::CopyFrom(const SetRoomPermsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.SetRoomPermsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetRoomPermsRequest::IsInitialized() const {
  return true;
}

void SetRoomPermsRequest::Swap(SetRoomPermsRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SetRoomPermsRequest::InternalSwap(SetRoomPermsRequest* other) {
  using std::swap;
  CastToBase(&perms_)->InternalSwap(CastToBase(&other->perms_));
  swap(family_id_, other->family_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string SetRoomPermsRequest::GetTypeName() const {
  return "wbapi.SetRoomPermsRequest";
}


// ===================================================================

void SetRoomPermsResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SetRoomPermsResponse::kErrorCodeFieldNumber;
const int SetRoomPermsResponse::kPerms0FieldNumber;
const int SetRoomPermsResponse::kPerms1FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SetRoomPermsResponse::SetRoomPermsResponse()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_room_5fperm_2eproto::scc_info_SetRoomPermsResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.SetRoomPermsResponse)
}
SetRoomPermsResponse::SetRoomPermsResponse(const SetRoomPermsResponse& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      perms0_(from.perms0_),
      perms1_(from.perms1_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  error_code_ = from.error_code_;
  // @@protoc_insertion_point(copy_constructor:wbapi.SetRoomPermsResponse)
}

void SetRoomPermsResponse::SharedCtor() {
  error_code_ = 0;
}

SetRoomPermsResponse::~SetRoomPermsResponse() {
  // @@protoc_insertion_point(destructor:wbapi.SetRoomPermsResponse)
  SharedDtor();
}

void SetRoomPermsResponse::SharedDtor() {
}

void SetRoomPermsResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SetRoomPermsResponse& SetRoomPermsResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_room_5fperm_2eproto::scc_info_SetRoomPermsResponse.base);
  return *internal_default_instance();
}


void SetRoomPermsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.SetRoomPermsResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  perms0_.Clear();
  perms1_.Clear();
  error_code_ = 0;
  _internal_metadata_.Clear();
}

bool SetRoomPermsResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.SetRoomPermsResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 error_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .wbapi.RoomPerm perms0 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_perms0()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .wbapi.RoomPerm perms1 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_perms1()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.SetRoomPermsResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.SetRoomPermsResponse)
  return false;
#undef DO_
}

void SetRoomPermsResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.SetRoomPermsResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error_code(), output);
  }

  // repeated .wbapi.RoomPerm perms0 = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->perms0_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2,
      this->perms0(static_cast<int>(i)),
      output);
  }

  // repeated .wbapi.RoomPerm perms1 = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->perms1_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3,
      this->perms1(static_cast<int>(i)),
      output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.SetRoomPermsResponse)
}

size_t SetRoomPermsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.SetRoomPermsResponse)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // repeated .wbapi.RoomPerm perms0 = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->perms0_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->perms0(static_cast<int>(i)));
    }
  }

  // repeated .wbapi.RoomPerm perms1 = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->perms1_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->perms1(static_cast<int>(i)));
    }
  }

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error_code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SetRoomPermsResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const SetRoomPermsResponse*>(&from));
}

void SetRoomPermsResponse::MergeFrom(const SetRoomPermsResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.SetRoomPermsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  perms0_.MergeFrom(from.perms0_);
  perms1_.MergeFrom(from.perms1_);
  if (from.error_code() != 0) {
    set_error_code(from.error_code());
  }
}

void SetRoomPermsResponse::CopyFrom(const SetRoomPermsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.SetRoomPermsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetRoomPermsResponse::IsInitialized() const {
  return true;
}

void SetRoomPermsResponse::Swap(SetRoomPermsResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SetRoomPermsResponse::InternalSwap(SetRoomPermsResponse* other) {
  using std::swap;
  CastToBase(&perms0_)->InternalSwap(CastToBase(&other->perms0_));
  CastToBase(&perms1_)->InternalSwap(CastToBase(&other->perms1_));
  swap(error_code_, other->error_code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string SetRoomPermsResponse::GetTypeName() const {
  return "wbapi.SetRoomPermsResponse";
}


// ===================================================================

void RoomPermsChangedNotification::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RoomPermsChangedNotification::kFamilyIdFieldNumber;
const int RoomPermsChangedNotification::kRoomIdFieldNumber;
const int RoomPermsChangedNotification::kUserIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RoomPermsChangedNotification::RoomPermsChangedNotification()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_room_5fperm_2eproto::scc_info_RoomPermsChangedNotification.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.RoomPermsChangedNotification)
}
RoomPermsChangedNotification::RoomPermsChangedNotification(const RoomPermsChangedNotification& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&family_id_, &from.family_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&user_id_) -
    reinterpret_cast<char*>(&family_id_)) + sizeof(user_id_));
  // @@protoc_insertion_point(copy_constructor:wbapi.RoomPermsChangedNotification)
}

void RoomPermsChangedNotification::SharedCtor() {
  ::memset(&family_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&user_id_) -
      reinterpret_cast<char*>(&family_id_)) + sizeof(user_id_));
}

RoomPermsChangedNotification::~RoomPermsChangedNotification() {
  // @@protoc_insertion_point(destructor:wbapi.RoomPermsChangedNotification)
  SharedDtor();
}

void RoomPermsChangedNotification::SharedDtor() {
}

void RoomPermsChangedNotification::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RoomPermsChangedNotification& RoomPermsChangedNotification::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_room_5fperm_2eproto::scc_info_RoomPermsChangedNotification.base);
  return *internal_default_instance();
}


void RoomPermsChangedNotification::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.RoomPermsChangedNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&family_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&user_id_) -
      reinterpret_cast<char*>(&family_id_)) + sizeof(user_id_));
  _internal_metadata_.Clear();
}

bool RoomPermsChangedNotification::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.RoomPermsChangedNotification)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 family_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &family_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 room_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &room_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 user_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &user_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.RoomPermsChangedNotification)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.RoomPermsChangedNotification)
  return false;
#undef DO_
}

void RoomPermsChangedNotification::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.RoomPermsChangedNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 family_id = 1;
  if (this->family_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->family_id(), output);
  }

  // int32 room_id = 2;
  if (this->room_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->room_id(), output);
  }

  // int64 user_id = 3;
  if (this->user_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->user_id(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.RoomPermsChangedNotification)
}

size_t RoomPermsChangedNotification::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.RoomPermsChangedNotification)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // int32 family_id = 1;
  if (this->family_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->family_id());
  }

  // int32 room_id = 2;
  if (this->room_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->room_id());
  }

  // int64 user_id = 3;
  if (this->user_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->user_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RoomPermsChangedNotification::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const RoomPermsChangedNotification*>(&from));
}

void RoomPermsChangedNotification::MergeFrom(const RoomPermsChangedNotification& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.RoomPermsChangedNotification)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.family_id() != 0) {
    set_family_id(from.family_id());
  }
  if (from.room_id() != 0) {
    set_room_id(from.room_id());
  }
  if (from.user_id() != 0) {
    set_user_id(from.user_id());
  }
}

void RoomPermsChangedNotification::CopyFrom(const RoomPermsChangedNotification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.RoomPermsChangedNotification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RoomPermsChangedNotification::IsInitialized() const {
  return true;
}

void RoomPermsChangedNotification::Swap(RoomPermsChangedNotification* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RoomPermsChangedNotification::InternalSwap(RoomPermsChangedNotification* other) {
  using std::swap;
  swap(family_id_, other->family_id_);
  swap(room_id_, other->room_id_);
  swap(user_id_, other->user_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string RoomPermsChangedNotification::GetTypeName() const {
  return "wbapi.RoomPermsChangedNotification";
}


// ===================================================================

void ListRoomPermsRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ListRoomPermsRequest::kFamilyIdFieldNumber;
const int ListRoomPermsRequest::kRoomIdFieldNumber;
const int ListRoomPermsRequest::kUserIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ListRoomPermsRequest::ListRoomPermsRequest()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_room_5fperm_2eproto::scc_info_ListRoomPermsRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.ListRoomPermsRequest)
}
ListRoomPermsRequest::ListRoomPermsRequest(const ListRoomPermsRequest& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&family_id_, &from.family_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&user_id_) -
    reinterpret_cast<char*>(&family_id_)) + sizeof(user_id_));
  // @@protoc_insertion_point(copy_constructor:wbapi.ListRoomPermsRequest)
}

void ListRoomPermsRequest::SharedCtor() {
  ::memset(&family_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&user_id_) -
      reinterpret_cast<char*>(&family_id_)) + sizeof(user_id_));
}

ListRoomPermsRequest::~ListRoomPermsRequest() {
  // @@protoc_insertion_point(destructor:wbapi.ListRoomPermsRequest)
  SharedDtor();
}

void ListRoomPermsRequest::SharedDtor() {
}

void ListRoomPermsRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ListRoomPermsRequest& ListRoomPermsRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_room_5fperm_2eproto::scc_info_ListRoomPermsRequest.base);
  return *internal_default_instance();
}


void ListRoomPermsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.ListRoomPermsRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&family_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&user_id_) -
      reinterpret_cast<char*>(&family_id_)) + sizeof(user_id_));
  _internal_metadata_.Clear();
}

bool ListRoomPermsRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.ListRoomPermsRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 family_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &family_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 room_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &room_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 user_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &user_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.ListRoomPermsRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.ListRoomPermsRequest)
  return false;
#undef DO_
}

void ListRoomPermsRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.ListRoomPermsRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 family_id = 1;
  if (this->family_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->family_id(), output);
  }

  // int32 room_id = 2;
  if (this->room_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->room_id(), output);
  }

  // int64 user_id = 3;
  if (this->user_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->user_id(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.ListRoomPermsRequest)
}

size_t ListRoomPermsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.ListRoomPermsRequest)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // int32 family_id = 1;
  if (this->family_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->family_id());
  }

  // int32 room_id = 2;
  if (this->room_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->room_id());
  }

  // int64 user_id = 3;
  if (this->user_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->user_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ListRoomPermsRequest::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ListRoomPermsRequest*>(&from));
}

void ListRoomPermsRequest::MergeFrom(const ListRoomPermsRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.ListRoomPermsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.family_id() != 0) {
    set_family_id(from.family_id());
  }
  if (from.room_id() != 0) {
    set_room_id(from.room_id());
  }
  if (from.user_id() != 0) {
    set_user_id(from.user_id());
  }
}

void ListRoomPermsRequest::CopyFrom(const ListRoomPermsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.ListRoomPermsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListRoomPermsRequest::IsInitialized() const {
  return true;
}

void ListRoomPermsRequest::Swap(ListRoomPermsRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ListRoomPermsRequest::InternalSwap(ListRoomPermsRequest* other) {
  using std::swap;
  swap(family_id_, other->family_id_);
  swap(room_id_, other->room_id_);
  swap(user_id_, other->user_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string ListRoomPermsRequest::GetTypeName() const {
  return "wbapi.ListRoomPermsRequest";
}


// ===================================================================

void ListRoomPermsResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ListRoomPermsResponse::kErrorCodeFieldNumber;
const int ListRoomPermsResponse::kFamilyIdFieldNumber;
const int ListRoomPermsResponse::kRoomIdFieldNumber;
const int ListRoomPermsResponse::kUserIdFieldNumber;
const int ListRoomPermsResponse::kPermsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ListRoomPermsResponse::ListRoomPermsResponse()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_room_5fperm_2eproto::scc_info_ListRoomPermsResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.ListRoomPermsResponse)
}
ListRoomPermsResponse::ListRoomPermsResponse(const ListRoomPermsResponse& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      perms_(from.perms_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&error_code_, &from.error_code_,
    static_cast<size_t>(reinterpret_cast<char*>(&room_id_) -
    reinterpret_cast<char*>(&error_code_)) + sizeof(room_id_));
  // @@protoc_insertion_point(copy_constructor:wbapi.ListRoomPermsResponse)
}

void ListRoomPermsResponse::SharedCtor() {
  ::memset(&error_code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&room_id_) -
      reinterpret_cast<char*>(&error_code_)) + sizeof(room_id_));
}

ListRoomPermsResponse::~ListRoomPermsResponse() {
  // @@protoc_insertion_point(destructor:wbapi.ListRoomPermsResponse)
  SharedDtor();
}

void ListRoomPermsResponse::SharedDtor() {
}

void ListRoomPermsResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ListRoomPermsResponse& ListRoomPermsResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_room_5fperm_2eproto::scc_info_ListRoomPermsResponse.base);
  return *internal_default_instance();
}


void ListRoomPermsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.ListRoomPermsResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  perms_.Clear();
  ::memset(&error_code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&room_id_) -
      reinterpret_cast<char*>(&error_code_)) + sizeof(room_id_));
  _internal_metadata_.Clear();
}

bool ListRoomPermsResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.ListRoomPermsResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 error_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 family_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &family_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 room_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &room_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 user_id = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &user_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .wbapi.RoomPerm perms = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_perms()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.ListRoomPermsResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.ListRoomPermsResponse)
  return false;
#undef DO_
}

void ListRoomPermsResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.ListRoomPermsResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error_code(), output);
  }

  // int32 family_id = 2;
  if (this->family_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->family_id(), output);
  }

  // int32 room_id = 3;
  if (this->room_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->room_id(), output);
  }

  // int64 user_id = 4;
  if (this->user_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->user_id(), output);
  }

  // repeated .wbapi.RoomPerm perms = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->perms_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      6,
      this->perms(static_cast<int>(i)),
      output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.ListRoomPermsResponse)
}

size_t ListRoomPermsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.ListRoomPermsResponse)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // repeated .wbapi.RoomPerm perms = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->perms_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->perms(static_cast<int>(i)));
    }
  }

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error_code());
  }

  // int32 family_id = 2;
  if (this->family_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->family_id());
  }

  // int64 user_id = 4;
  if (this->user_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->user_id());
  }

  // int32 room_id = 3;
  if (this->room_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->room_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ListRoomPermsResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ListRoomPermsResponse*>(&from));
}

void ListRoomPermsResponse::MergeFrom(const ListRoomPermsResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.ListRoomPermsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  perms_.MergeFrom(from.perms_);
  if (from.error_code() != 0) {
    set_error_code(from.error_code());
  }
  if (from.family_id() != 0) {
    set_family_id(from.family_id());
  }
  if (from.user_id() != 0) {
    set_user_id(from.user_id());
  }
  if (from.room_id() != 0) {
    set_room_id(from.room_id());
  }
}

void ListRoomPermsResponse::CopyFrom(const ListRoomPermsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.ListRoomPermsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListRoomPermsResponse::IsInitialized() const {
  return true;
}

void ListRoomPermsResponse::Swap(ListRoomPermsResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ListRoomPermsResponse::InternalSwap(ListRoomPermsResponse* other) {
  using std::swap;
  CastToBase(&perms_)->InternalSwap(CastToBase(&other->perms_));
  swap(error_code_, other->error_code_);
  swap(family_id_, other->family_id_);
  swap(user_id_, other->user_id_);
  swap(room_id_, other->room_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string ListRoomPermsResponse::GetTypeName() const {
  return "wbapi.ListRoomPermsResponse";
}


// ===================================================================

void DeleteRoomPermsRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DeleteRoomPermsRequest::kFamilyIdFieldNumber;
const int DeleteRoomPermsRequest::kRoomIdFieldNumber;
const int DeleteRoomPermsRequest::kUserIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DeleteRoomPermsRequest::DeleteRoomPermsRequest()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_room_5fperm_2eproto::scc_info_DeleteRoomPermsRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.DeleteRoomPermsRequest)
}
DeleteRoomPermsRequest::DeleteRoomPermsRequest(const DeleteRoomPermsRequest& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&family_id_, &from.family_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&user_id_) -
    reinterpret_cast<char*>(&family_id_)) + sizeof(user_id_));
  // @@protoc_insertion_point(copy_constructor:wbapi.DeleteRoomPermsRequest)
}

void DeleteRoomPermsRequest::SharedCtor() {
  ::memset(&family_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&user_id_) -
      reinterpret_cast<char*>(&family_id_)) + sizeof(user_id_));
}

DeleteRoomPermsRequest::~DeleteRoomPermsRequest() {
  // @@protoc_insertion_point(destructor:wbapi.DeleteRoomPermsRequest)
  SharedDtor();
}

void DeleteRoomPermsRequest::SharedDtor() {
}

void DeleteRoomPermsRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DeleteRoomPermsRequest& DeleteRoomPermsRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_room_5fperm_2eproto::scc_info_DeleteRoomPermsRequest.base);
  return *internal_default_instance();
}


void DeleteRoomPermsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.DeleteRoomPermsRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&family_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&user_id_) -
      reinterpret_cast<char*>(&family_id_)) + sizeof(user_id_));
  _internal_metadata_.Clear();
}

bool DeleteRoomPermsRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.DeleteRoomPermsRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 family_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &family_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 room_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &room_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 user_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &user_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.DeleteRoomPermsRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.DeleteRoomPermsRequest)
  return false;
#undef DO_
}

void DeleteRoomPermsRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.DeleteRoomPermsRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 family_id = 1;
  if (this->family_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->family_id(), output);
  }

  // int32 room_id = 2;
  if (this->room_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->room_id(), output);
  }

  // int64 user_id = 3;
  if (this->user_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->user_id(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.DeleteRoomPermsRequest)
}

size_t DeleteRoomPermsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.DeleteRoomPermsRequest)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // int32 family_id = 1;
  if (this->family_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->family_id());
  }

  // int32 room_id = 2;
  if (this->room_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->room_id());
  }

  // int64 user_id = 3;
  if (this->user_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->user_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DeleteRoomPermsRequest::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const DeleteRoomPermsRequest*>(&from));
}

void DeleteRoomPermsRequest::MergeFrom(const DeleteRoomPermsRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.DeleteRoomPermsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.family_id() != 0) {
    set_family_id(from.family_id());
  }
  if (from.room_id() != 0) {
    set_room_id(from.room_id());
  }
  if (from.user_id() != 0) {
    set_user_id(from.user_id());
  }
}

void DeleteRoomPermsRequest::CopyFrom(const DeleteRoomPermsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.DeleteRoomPermsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeleteRoomPermsRequest::IsInitialized() const {
  return true;
}

void DeleteRoomPermsRequest::Swap(DeleteRoomPermsRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DeleteRoomPermsRequest::InternalSwap(DeleteRoomPermsRequest* other) {
  using std::swap;
  swap(family_id_, other->family_id_);
  swap(room_id_, other->room_id_);
  swap(user_id_, other->user_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string DeleteRoomPermsRequest::GetTypeName() const {
  return "wbapi.DeleteRoomPermsRequest";
}


// ===================================================================

void DeleteRoomPermsResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DeleteRoomPermsResponse::kErrorCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DeleteRoomPermsResponse::DeleteRoomPermsResponse()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_room_5fperm_2eproto::scc_info_DeleteRoomPermsResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:wbapi.DeleteRoomPermsResponse)
}
DeleteRoomPermsResponse::DeleteRoomPermsResponse(const DeleteRoomPermsResponse& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  error_code_ = from.error_code_;
  // @@protoc_insertion_point(copy_constructor:wbapi.DeleteRoomPermsResponse)
}

void DeleteRoomPermsResponse::SharedCtor() {
  error_code_ = 0;
}

DeleteRoomPermsResponse::~DeleteRoomPermsResponse() {
  // @@protoc_insertion_point(destructor:wbapi.DeleteRoomPermsResponse)
  SharedDtor();
}

void DeleteRoomPermsResponse::SharedDtor() {
}

void DeleteRoomPermsResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DeleteRoomPermsResponse& DeleteRoomPermsResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_room_5fperm_2eproto::scc_info_DeleteRoomPermsResponse.base);
  return *internal_default_instance();
}


void DeleteRoomPermsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:wbapi.DeleteRoomPermsResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  error_code_ = 0;
  _internal_metadata_.Clear();
}

bool DeleteRoomPermsResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:wbapi.DeleteRoomPermsResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 error_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:wbapi.DeleteRoomPermsResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:wbapi.DeleteRoomPermsResponse)
  return false;
#undef DO_
}

void DeleteRoomPermsResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:wbapi.DeleteRoomPermsResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error_code(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:wbapi.DeleteRoomPermsResponse)
}

size_t DeleteRoomPermsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wbapi.DeleteRoomPermsResponse)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // int32 error_code = 1;
  if (this->error_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error_code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DeleteRoomPermsResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const DeleteRoomPermsResponse*>(&from));
}

void DeleteRoomPermsResponse::MergeFrom(const DeleteRoomPermsResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:wbapi.DeleteRoomPermsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.error_code() != 0) {
    set_error_code(from.error_code());
  }
}

void DeleteRoomPermsResponse::CopyFrom(const DeleteRoomPermsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wbapi.DeleteRoomPermsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeleteRoomPermsResponse::IsInitialized() const {
  return true;
}

void DeleteRoomPermsResponse::Swap(DeleteRoomPermsResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DeleteRoomPermsResponse::InternalSwap(DeleteRoomPermsResponse* other) {
  using std::swap;
  swap(error_code_, other->error_code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string DeleteRoomPermsResponse::GetTypeName() const {
  return "wbapi.DeleteRoomPermsResponse";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace wbapi
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::RoomPerm* Arena::CreateMaybeMessage< ::wbapi::RoomPerm >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::RoomPerm >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::SetRoomPermsRequest* Arena::CreateMaybeMessage< ::wbapi::SetRoomPermsRequest >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::SetRoomPermsRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::SetRoomPermsResponse* Arena::CreateMaybeMessage< ::wbapi::SetRoomPermsResponse >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::SetRoomPermsResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::RoomPermsChangedNotification* Arena::CreateMaybeMessage< ::wbapi::RoomPermsChangedNotification >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::RoomPermsChangedNotification >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::ListRoomPermsRequest* Arena::CreateMaybeMessage< ::wbapi::ListRoomPermsRequest >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::ListRoomPermsRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::ListRoomPermsResponse* Arena::CreateMaybeMessage< ::wbapi::ListRoomPermsResponse >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::ListRoomPermsResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::DeleteRoomPermsRequest* Arena::CreateMaybeMessage< ::wbapi::DeleteRoomPermsRequest >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::DeleteRoomPermsRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::wbapi::DeleteRoomPermsResponse* Arena::CreateMaybeMessage< ::wbapi::DeleteRoomPermsResponse >(Arena* arena) {
  return Arena::CreateInternal< ::wbapi::DeleteRoomPermsResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
